### ISSUE TITLE
Migrate FRAME issues over to the Polkadot SDK monorepo

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk#1]
```[tasklist]
### Tasks
- [x] Issues from [Runtime / FRAME](https://github.com/orgs/paritytech/projects/40)
- [x] Issues from [Benchmarking and Weights](https://github.com/orgs/paritytech/projects/47)
- [x] Issues from [(Nominated) Proof of Stake](https://github.com/orgs/paritytech/projects/33)
```
