### ISSUE TITLE
[P-K Bridge] AssetHubs - create wrapped/derivate representations for KSM/DOT

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#1016]
We need to create `ForeignAssets`  for wrappedKSM on AssetHubPolkadot and wrappedDOT on AssetHubKusama.

**Options:** (lets consider **wrappedDOT** on **AssetHubKusama**)
1. use `pallet_assets::force_create` on Kusama/AssethubKusama governance call
     ```
     force_create(
         MultiLocation(parents: 2, X1(GlobalConsensus(Polkadot))),
         SOVEREIGN_ACCOUNT,
         is_sufficient=false,
         min_balance=?
     )
     ```
  - what SOVEREIGN_ACCOUNT -> SA_OF_ASSET_HUB_POLKADOT(`MultiLocation(parents: 2, X2(GlobalConsensus(Polkadot), Parachain(1000))`)  or SA_OF_POLKADOT(`MultiLocation(parents: 2, X1(GlobalConsensus(Polkadot)))`)
  - what `min_balance` ?
2.  use `pallet_assets::create` from Polkadot relaychain
     ```
     create(
         MultiLocation(parents: 2, X1(GlobalConsensus(Polkadot))),
         ADMIN_ACCOUNT,
         min_balance=?
     )
     ```
  - what ADMIN_ACCOUNT: SA of Polkadot relay chain or SA of AssetHubPolkadot?
  - what `min_balance` ?
  - **this means to extend/add XCM bridge routing to polkadot runtime**
3. option: anything else because `ForeignCreators` wont work for `MultiLocation::parent()` and AssetHubPolkadot

---
**TODOs**
- [ ] resolve what option
- [ ] prepare governance calls and referenda/proposals - for ForeignAssets
- [ ] prepare governance calls and referenda/proposals - for HRMP and/or other stuff
