### ISSUE TITLE
[P-K Bridge] AssetHubs - withdraw reserve asset transfer (opposite direction)

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#1020]
simple scenario: **(move back and forth KSM from AssetHubKusama to AssetHubPolkadot)**
- AssetHubKusama does reserve for KSM -> `ReserveAssetDeposited(KSM)` -> AssetHubPolkadot receive pKSM
- way back AssetHubPolkadot burn pKSM-> `WithdrawAsset(pKSM)` -> AssetHubKusama withdraw reserve of KSM

---
we have two PoC for reserve based tranfer:

1. PoC - with custom extrinsic supports both ways (way back withtout `InitiateReserveWithdraw` instruction)  - https://github.com/paritytech/cumulus/pull/2013
2. PoC - with `pallet_xcm` - https://github.com/paritytech/cumulus/pull/2762
    - supports only `reserve_asset_transfer`
    - `pallet_xcm` does not even support `reserve_withdraw_assets` yet
      - there exists unfinished/unmerged attempt https://github.com/paritytech/polkadot/pull/5975 

---
**TODOs/open questions:**

- [ ] ~~why `pallet_xcm` does not support `InitiateReserveWithdraw` is there a reason for that?~~
- [ ] ~~what about AssetHubs - do they have to implement their custom logic/extrinsic for `InitiateReserveWithdraw`?~~ no, need to finish pallet_xcm [PR](https://github.com/paritytech/polkadot/pull/5975)
- [ ] what should be a good design for `InitiateReserveWithdraw` and/or are there any caveats?

---
**Note:** For BHK/P makes sense only when **Kusama governance gives up sovereignty and accepts Polkadot.**, which means: 
From discussion:: https://matrix.to/#/!nYxxyvMNMUaniRIokh:parity.io/$nLYDBTVX1Cb6wn5Q_g2uCg5urRl6h71kLvxNVkyAI1A?via=parity.io&via=web3.foundation

> It means, that Kusama has to accept "Polkadot Fellowship (collectives-polkadot)" origins over bridge at first?
> runtime upgrade with some trusted origin configuration on Kusama

> It would mean Kusama removes most of its governance logic and maps its origins to the corresponding origins on Polkadot (e.g. StakingAdmin becomes PolkadotStakingAdmin) via runtime upgrade.
