### ISSUE TITLE
Bridge Security audit 

### ISSUE THREAD

**Issue by svyatonik** [paritytech/polkadot-sdk#1087]
Pending audit:
- [x] [Bridge Parachains Finality Pallet](https://github.com/paritytech/parity-bridges-common/tree/master/modules/parachains);
- [x] [Bridge Messages Palet](https://github.com/paritytech/parity-bridges-common/tree/master/modules/messages);
- [x] [Bridge GRANDPA Pallet](https://github.com/paritytech/parity-bridges-common/tree/master/modules/grandpa);
- [x] [Bridge Relayers Pallet](https://github.com/paritytech/parity-bridges-common/tree/master/modules/relayers);
- [x] [Signed Extension to Refund relayers](https://github.com/paritytech/parity-bridges-common/blob/master/bin/runtime-common/src/refund_relayer_extension.rs).

Future audit:
- [x] Bridge Hub runtimes. Now they live in a separate branch: https://github.com/paritytech/cumulus/tree/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/bridge-hub-rococo. Will probably be merged before audit;
- ~[ ] `pallet-bridge-transfer` pallet. Now it also lives in a separate branch here: https://github.com/paritytech/cumulus/tree/bko-transfer-asset-via-bridge/parachains/pallets/bridge-transfer. Will probably be merged before audit~;
- [x] Glue code to link runtime and bridge pallets together. It'll be in the same branch as (1). Now it is here: https://github.com/paritytech/cumulus/tree/bridge-hub-rococo-wococo/bridges/bin/runtime-common;
- [ ] paritytech/parity-bridges-common#1904
- [ ] paritytech/parity-bridges-common#1990
- [x] (very maybe - PRs are trivial imo) weight v2 optimization PRs (#1861, paritytech/parity-bridges-common#1863, paritytech/parity-bridges-common#1868, paritytech/parity-bridges-common#1871, paritytech/parity-bridges-common#1864).
