### ISSUE TITLE
Wasm Contracts: Implement Code Merkleization

### ISSUE THREAD

**Issue by athei** [paritytech/polkadot-sdk#122]
## Glossary
- **Substrate Runtime**: The execution path of the cumulus derived runtime that runs on the parachain nodes (full node, collator).
- **PVF**: The execution path of the cumulus derived runtime that runs on the relay chain validators.
- **PoV**: Data passed by collators to the validators for validation. For our case we can assume that to be `(block_header, extrinsics, storage_proof)`

## Motivation

In the current `pallet-contracts` implementation the whole wasm binary of a contract needs to be loaded from storage into memory before it can be executed. Therefore any `call` transaction triggers all the code to be included in the proof of value when executed on a parachain. This is because right now the merkle proof that is sent from the collator to the validator is automatically recorded form the accessed storage items.

One way of reducing the PoV size we want to explore is to opt out of this automatic recording for the (big) storage item that contains the contract code and instead provide a custom merkle proof containing only the accessed parts of the contract.

## Description

We leave the actual storage as-is (contract stays in a single storage item) but record which parts of a contract are executed when running a contract call in the substrate runtime (as opposed to PVF). This information can then be used to stitch together a partial wasm module in the PVF (run by the validator). Note that this partial wasm module would be constructed in a way that it can be executed by any execution engine.

The code would be merkelized on deploy time by the substrate runtime according to our chunking strategy (one chunk per function to keep it simple for now). The root of that merkle tree would be put in regular storage and a proof against that root is put into the PoV for every call of that contract. The code is still stored as a single storage item. The merkle tree is only for the proof that is received by the PVF.

This approach has several advantages:
- No need to add changes or complexity to execution engines
    - Coverage collection (selecting which chunks are used) will be done by instrumentation (not in the execution engine)
    - wasmer, wasmi, ... can be used as-is
- No additional storage access overhead in the substrate runtime since code stays in a single storage item
- Easier storage migration when chunking strategy or tree flavor changes

**However**, this can't be implemented with the current state of substrate/cumulus because any storage access of the substrate runtime is recorded and put into the PoV.  One idea to resolve that is to give the runtime logic more control over the storage contents of the PoV: We think that we need exclude the access to the original monolithic wasm code entry from the automatically generated storage proof and instead include our custom proof. In order to do so cumulus would need to be modified to allow its users (the actual runtime, the pallets, etc...) to put custom data into the [`ParachainBlockData`](https://github.com/paritytech/cumulus/blob/47b368ea5cb67bbd8d3b51494048b92b3c0ca640/primitives/core/src/lib.rs#L147-L159) (which is essentially the PoV).

This is a departure from the current design where the runtime logic is oblivious to the fact that it  is running as a para chain. This might sound bad but it will enable use cases where pallets can provide data much more efficiently to the validators:
- No need to put data in storage just to send it to the validator.
- Using proof systems that are specifically tailored to the use case.

## Progress

- [x] Figure out the proper chunking strategy by writing instrumentation/tooling that can be used to observe the execution of contracts paritytech/substrate#9481: **We use one chunk per function as a MVP because we can change this later.**
- [ ] Figure out a way to change CUMULUS and FRAME to include a custom proof.
- [ ] Figure out which trie type and node key strategy minimize the merkle witness.
- [ ] Implement code merkelization in pallet_contracts.

**Comment by athei** [comment]
No longer planned: Instead, we should allow storage of contract code on the relay chain for an additional deposit. In case proof size turns out to be a bottle neck.
