### ISSUE TITLE
GHW - RC Automation

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-sdk#1273]
Best is to start from [release-10_rc-automation.yml](https://github.com/paritytech/cumulus/blob/master/.github/workflows/release-10_rc-automation.yml) from Cumulus.

## todo:

- [x] refactor to the bash script to a lib
- [x] add branches for all products
- [x] use GH conditions (`if:`) if special treatments are required

**Comment by EgorPopelyaev** [comment]
work in progress in https://github.com/paritytech/polkadot-sdk/pull/1574

**Comment by EgorPopelyaev** [comment]
Closed with #1574
