### ISSUE TITLE
[Deprecation] Treasury Proposal Dispatchables 

### ISSUE THREAD

**Issue by muharem** [paritytech/polkadot-sdk#138]
The old treasury pallet's dispatchables to create/reject/approve a proposal now replaced by the `spend` dispatchable.

Deprecated dispatchables:
- pallet_treasury.propose_spend
- pallet_treasury.reject_proposal
- pallet_treasury.approve_proposal

The `pallet_treasury.remove_approval` dispatchable is not deprecated since its still can be used to remove an approved proposal by the `spend`.

```[tasklist]
### Tasks
- [x] Hard deprecation by adding a warning message - https://github.com/paritytech/substrate/pull/14538
- [x] Remove usage of the deprecated feature in the code base
- [x] Update examples and tutorials
- [x] Deprecation is noted in the release log
- [x] Removal version is planned
- [x] Deprecated feature is removed
- [x] Removal of the feature is noted in the release log
```

**Comment by ozgunozerk** [comment]
Hi @muharem! I'm confused by the explanations provided for the deprecation:

> - `propose_spend` will be removed in February 2024. Use `spend` instead.
> - `reject_proposal` will be removed in February 2024. Use `spend` instead.
> - `approve_proposal` will be removed in February 2024. Use `spend` instead.

My confusion is, from what I understood, it was possible to `propose` a spend previously (but not approve it yet), and there was a `proposed, but not approved` state tracked with the `Proposals` storage item.

Now, all the to be deprecated functions above, and `Proposals` storage item will be removed, along with `Proposed` and `Rejected` events.

So, after this change, it will be impossible to solely propose (but not approve) a spend? 

My understanding is that, only approved proposals will be tracked on this pallet. What about proposed but not yet approved spends? Where will they be tracked? Or if they won't be tracked, why? Is there an explanation on these that I can follow? 

From the docs and sourcecode, these remained unclear to me.

Thanks in advance!

**Comment by ozgunozerk** [comment]
Also, another relevant question about the diff between `spend_local` and `spend` dispatchables:

- `spend_local` function proposes and approves the spend. In the sourcecode, we can see that there is this line:
    ```rust
    Approvals::<T, I>::try_append(proposal_index)
    ```
- however, in `spend` function, I couldn't find any clues that lead to the proposal being appended to `Approvals` storage item.

Also, why is there a `valid_from` field in `spend`, but not in `spend_local`?

**Comment by muharem** [comment]
Hi @ozgunozerk 
Yes, you are right, without those calls, there wont be a way to track un approved proposals solely with this pallet.
The idea to use this pallet with some other pallet which will provide that functionality. For Polkadot it's OpenGov (referenda and conviction voting pallets).
The storage items wont be removed though for now, because they are used for `spend_local`.

`spend_local` is renamed old `spend` calls, and it has not changes like `valid_from` for backward compatibility. 
You can find here more details on how we use new `spend` call - https://forum.polkadot.network/t/multi-asset-treasury-and-milestone-based-spends/6780
