### ISSUE TITLE
[Deprecation] deprecate "old" weight items

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk#144]
The deprecated items in `frame/support/src/weights.rs` need to be removed

```[tasklist]
### Tasks
- [x] Hard deprecation by adding a warning message
- [x] Remove usage of the deprecated feature in the code base
- [ ] Update examples and tutorials https://github.com/substrate-developer-hub/substrate-docs/issues/2036
- [x] ~Deprecation is noted in the release log~
- [x] ~Removal version is planned~
- [x] Deprecated feature is removed https://github.com/paritytech/substrate/pull/14706
- [ ] Removal of the feature is noted in the release log
```

**Comment by ggwpez** [comment]
`sp_weights::OldWeight` remains and can now be removed.

**Comment by philoniare** [comment]
Can I work on this? @ggwpez @juangirini

**Comment by ggwpez** [comment]
Yea sure 😄
