### ISSUE TITLE
Secure validator mode

### ISSUE THREAD

**Issue by mrcnski** [paritytech/polkadot-sdk#1444]
## Overview

**Summary:** Running `--validator` on a platform other than Linux x86-64 requires the `--insecure-validator-i-know-what-i-do flag`.

Due to https://github.com/paritytech/polkadot-sdk/issues/882 becoming high-priority for parathreads, we are now forced to provide a secure validator mode only for Linux x86-64 (to start).

We will still support other platforms with an `--insecure-validator-i-know-what-i-do flag`. (Naming follows [interpreted-i-know-what-i-do](https://github.com/paritytech/substrate/blob//client/cli/src/arg_enums.rs?rgh-link-date=2023-04-13T13%3A54%3A01Z#L58).)

## Todo

Preparation:
- [x] Announce this change to validators ahead of time in a release notes https://github.com/w3f/polkadot-wiki/issues/4881
- [x] Document secure-mode. https://github.com/w3f/polkadot-wiki/pull/5346
- [x] Make unavailable security features print a warning that says this will soon be required to run securely, with a link to the announcement. https://github.com/paritytech/polkadot-sdk/pull/2244

Code:
- [x] Make all candidate-validation security features a requirement to run in secure-mode.
  - [x] Exception: if one FS feature is missing and the other is present, that's fine.
- [x] Have a flag to run in "insecure mode"
- [x] When running in secure-mode, link to https://wiki.polkadot.network/docs/maintain-guides-secure-validator on startup.

Followup:
- [ ] Add automatically flag to zombienet

## Related

Previous draft PR: https://github.com/paritytech/polkadot/pull/7073
Proposed announcement: https://github.com/w3f/polkadot-wiki/issues/4881

**Comment by pepoviola** [comment]
Just a note to me. We should add the logic to enable the flag automatically in zombienet so users can still run from the current configs.

**Comment by mrcnski** [comment]
Currently the "can-unshare-and-change-root" capability is required for secure-mode. But we just had a user for whom it failed: https://github.com/paritytech/polkadot-sdk/pull/2304 *However*, he was on a Linux version (5.15) which should support Landlock. So I think that *either* the unshare capability *or* the Landlock capability should be present, since either provides filesystem security. This way the user can still run securely without a CLI flag. :)

**Comment by mrcnski** [comment]
Hi @hitchhooker! I *think* you should be fine:

- The landlock error is most likely because the Linux version you are using doesn't support it. It is optional if the unshare-and-change-root capability is available.
- The unshare-and-change-root error is likely due to this bug which has been fixed: https://github.com/paritytech/polkadot-sdk/pull/2426 You can verify whether it was fixed for you by running the latest `master`.

If all else fails, you will have the option to disable this error with a CLI flag. If you see the error on the next release, it will tell you exactly what to do.

I hope that helps!

**Comment by hitchhooker** [comment]
```
Dec 14 13:33:59 ksm04 polkadot[418871]: 2023-12-14 13:33:59 🚨 Some security issues have been detected.
Dec 14 13:33:59 ksm04 polkadot[418871]: Running validation of malicious PVF code has a higher risk of compromising this machine.
Dec 14 13:33:59 ksm04 polkadot[418871]:   - Optional: Cannot enable landlock, a Linux 5.13+ kernel security feature: not available: Could not fully enable: NotEnforced
Dec 14 13:33:59 ksm04 polkadot[418871]: 2023-12-14 13:33:59 👮‍♀️ Running in Secure Validator Mode. It is highly recommended that you operate according to our security guidelines.
Dec 14 13:33:59 ksm04 polkadot[418871]: More information: https://wiki.polkadot.network/docs/maintain-guides-secure-validator#secure-validator-mode
```
```
root@bkk04  𓅨 ~
7794 🕸 cat /boot/config-`uname -r` | grep CONFIG_SECCOMP=                                                                       ⏎ [~]
CONFIG_SECCOMP=y
root@bkk04  𓅨 ~
7796 🕸 pct enter 124                                                                                                            ⏎ [~]
root@ksm04:~# cat /boot/config-`uname -r` | grep CONFIG_SECCOMP=
cat: /boot/config-6.2.16-10-pve: No such file or **directory**
```
so any instructiuons how do I run secure validator setup inside lx containers?

**Comment by hitchhooker** [comment]
```
root@bkk04  𓅨 ~
7800 🕸 dmesg | grep landlock || journalctl -kg landlock                                                                           [~]
-- No entries --
root@bkk04  𓅨 ~
7801 🕸 pct enter 124                                                                                                            ⏎ [~]
root@ksm04:~# dmesg | grep landlock || journalctl -kg landlock
dmesg: read kernel buffer failed: Operation not permitted
-- No entries --
root@ksm04:~#
```
I guess we lack permissions for dmesg inside the container.
