### ISSUE TITLE
[Deprecation] Remove `Balances::set_balance_deprecated`

### ISSUE THREAD

**Issue by juangirini** [paritytech/polkadot-sdk#147]
`force_set_balance` should be used instead
```[tasklist]
### Tasks
- [x] ~Hard deprecation by adding a warning message *~
- [x] Remove usage of the deprecated feature in the code base
- [ ] https://github.com/substrate-developer-hub/substrate-docs/issues/2056
- [x] ~Deprecation is noted in the release log~
- [x] Removal version is planned
- [x] Deprecated feature is removed
- [x] Removal of the feature is noted in the release log
```

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-release-analysis-v1-2-0/4451/1
