### ISSUE TITLE
[TryRuntime] Tracking Issue for road to stable, easily usable migrations & a try-runtime-cli "V1"

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#178]
This is a wrapper issue for Parity Roadmap. 

### Overview

`try-runtime-cli` is a tool used to test development runtimes against production chain state, it has become a indispensable tool for testing migrations and new logic. However there are some areas where the developer experience of using the tool can be improved, and also areas in which the internal `try-runtime` feature gated code could be refactored to be more robust and easy to use. This issue tracks the core improvements we would like to implement for the `try-runtime-cli`, and its capabilities via `try-runtime` feature gated code by the end of the year.

### try-runtime-cli improvements
- [x] https://github.com/paritytech/try-runtime-cli/issues/13
- [x] https://github.com/paritytech/substrate/issues/12975
- [x] https://github.com/paritytech/try-runtime-cli/issues/12
- [x] Improve docs

### try-runtime improvements
- [ ] https://github.com/paritytech/polkadot-sdk/issues/239
- [x] https://github.com/paritytech/substrate/issues/13107
- [x] https://github.com/paritytech/polkadot-sdk/issues/109
    - https://github.com/paritytech/substrate/pull/14641
- [x] https://github.com/paritytech/substrate/issues/13681

**Comment by liamaharon** [comment]
I think adding try-state for all pallets is out of scope for this issue. will remove that point and close it.
