### ISSUE TITLE
Vision: Pallet syntax improvement

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#187]
Some ideas that came up in recent meetings and discussions on how to improve the pallet syntax:
- [ ] Removing the explicit `generate_deposit` and rather having a `deposit` function on the event type itself (eg via `#[derive(Ddeposit)]`).
- [ ] Making the `<T>` on the pallet `Event` and `Error` optional https://github.com/paritytech/polkadot-sdk/issues/176.
- [x] Getting rid of trivial `#[pallet::weight(T::WeightInfo::call())]` by having a pallet `weight_info` pallet attribute that provides the `WeightInfo` and then tries to pull it from there https://github.com/paritytech/substrate/pull/13932.
- [ ] Breaking pallets into smaller parts: https://github.com/paritytech/substrate/pull/13950
- [x] Default hashers in dev-mode https://github.com/paritytech/substrate/issues/13263
- [ ] (unconfirmed) Removing `fn getters`: https://github.com/paritytech/substrate/pull/13365 / https://github.com/paritytech/substrate/issues/13259
- [ ] Check if we need `generate_storage_info`

Please edit to extend.

**Comment by kianenigma** [comment]
> Making the <T> on the pallet Event and Error optional

I am not sure if this is the way forward tbh. I wish I could come up with a single rule that would rule all of the `#[pallet]` enhanced types, but especially because of `Event` and `GenesisConfig`, I cannot. These two can correctly have no generic, and this makes it tricky.
