### ISSUE TITLE
[testnet] Rococo/Westend bridge-related redeployment

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#1988]
This issue summarize a big redeployment plan for testnets.

# Rococo
- [x] BridgeHubRococo
  - actual version: `bridge-hub-rococo/9420` some old version from Cumulus
  - [x] desired version: `bridge-hub-rococo-runtime` master/release branch from `polkadot-sdk` `bridge-hub-rococo/1003000`
  - calls:
    - [x] (governance) init bridge to Westend https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1790355331
    - [x] (faucet) drip relayer accounts - part of https://github.com/paritytech/devops/issues/2922
    - [x] (faucet) drip SA of AssetHubRococo [`5Eg2fntNprdN3FgH4sfEaaZhYtddZQSQUqvYJ1f2mLtinVhV`](https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/scripts/bridges_rococo_westend.sh#L65)
    - [x] (governance) `forceDefaultXcmVersion(3)` on BridgeHubRococo
    - [x] (governance) `forceXcmVersion` on BridgeHubRococo for BridgeHubWestend https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1882989945 (for `pallet-xcm-bridge-hub` version check)
- [x] AssetHubRococo
  - actual version: `statemine/10005`  old Cumulus  `asset-hub-kusama-runtime` release for Rockmine 10005
  - [x] desired version: `asset-hub-rococo-runtime` master/release branch from `polkadot-sdk` `statemine/1003000`
  - calls:
    - [x] (governance) HRMP to BridgeHubRococo
    - [x] (governance) force create asset for wrapped WND 
    - [x] (governance) set metadata for wrapped WND https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1810110927
    - [x] (governance) `forceXcmVersion` on AssetHubRococo for BridgeHubRococo https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1816162502  (for `XcmpQueue`)
    - [x] (governance) `forceXcmVersion` on AssetHubRococo for AssetHubWestend https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1882985873  (for `pallet-xcm-bridge-hub-router` version check)

# Westend
- [x] BridgeHubWestend
  - actual version: `bridge-hub-kusama/9430` - some old version `bridge-hub-kusama-runtime` from Cumulus
  - [x] desired version: `bridge-hub-rococo-runtime` master/release branch from `polkadot-sdk` `bridge-hub-westend/1003000`
  - calls:
    - [x] (governance) init bridge to Rococo https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1790352753
    - [x] (faucet) drip relayer accounts - part of https://github.com/paritytech/devops/issues/2922
    - [x] (faucet) drip SA of AssetHubWestend [`5Eg2fntNprdN3FgH4sfEaaZhYtddZQSQUqvYJ1f2mLtinVhV`](https://github.com
    - [x] (governance) `forceDefaultXcmVersion(3)` on BridgeHubWestend https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1816477737
    - [x] (governance) `forceXcmVersion` on BridgeHubWestend for AssetHubWestend https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1816509109
    - [x] (governance) `forceXcmVersion` on BridgeHubWestend for BridgeHubRococo https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1883161069 (for `pallet-xcm-bridge-hub` version check)
- [x] AssetHubWestend
  - actual version:  `westmint/9435`
  - [x] desired version: `asset-hub-westend-runtime` master/release branch from `polkadot-sdk` `westmint/1003000`
  - governance calls
    - [x] (governance) HRMP to BridgeHubWestend
    - [x] (governance) force create asset for wrapped ROC
    - [x] (governance) set metadata for wrapped ROC **after upgrade** https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1810114301
    - [x] (governance) `forceXcmVersion` on AssetHubWestend for BridgeHubWestend https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1816211898
  - [x] check `NativeAssetParents0ToParents1Migration` after upgrade
  - [x] (governance) `forceXcmVersion` on AssetHubWestend for AssetHubRococo https://github.com/paritytech/parity-bridges-common/issues/2602#issuecomment-1883161069  (for `pallet-xcm-bridge-hub-router` version check)

# Other

- [x] setup relayer Rococo<->Westend https://github.com/paritytech/devops/issues/2922
- [ ] setup equivocation detector for Rococo<>Westend - [issue](https://github.com/paritytech/parity-bridges-common/issues/2709)
- [x] setup monitoring/alerts (copy of Rococo<>Wococo)
  - [x] check prometheus params: `--prometheus-host 0.0.0.0` and `--prometheus-port 9615`
  - [x] make sure `https://thanos.parity-mgmt.parity.io` Thanos metrics are accesible for `substrate-relay`
- [x] setup periodic job for asset transfer (copy of Rococo<>Wococo ) https://github.com/paritytech/devops/issues/2958
- [x] check `srtool` to support `asset-hub-rococo`: https://github.com/paritytech/srtool/actions/workflows/manual-polkadot-sdk.yml
- [x] check `srtool` to support `bridge-hub-westend`: https://github.com/paritytech/srtool/actions/workflows/manual-polkadot-sdk.yml https://github.com/paritytech/srtool/issues/76

# After Rococo<>Westend works
- [x] remove Rockmine2 (Rococo's second temporary AssetHub) https://github.com/paritytech/devops/issues/2950
- [x] remove Wockmint (Wococo's AssetHub) https://github.com/paritytech/devops/issues/2924
- [x] close all related issues/points:
  - https://github.com/paritytech/polkadot-sdk/issues/1128
  - https://github.com/paritytech/polkadot-sdk/pull/1215
  - https://github.com/paritytech/parity-bridges-common/issues/2602
- [ ] sumarize steps in one comment (for P<>K bridge)
