### ISSUE TITLE
Coretime Zombienet Test

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#2310]
Setup a Zombienet with coretime parachain and make it send an assignment over to the relay chain. See it getting served. (Second parachain)

Network must be bootstrapped - coretime chain must have a core on the relay chain pre-configured.

# Tasks

- [x] Fix Westend (migrations)
- [x] Fix Rococo - remove WeightInfo
- [ ] Make CI pass
- [ ] Add dummy WeightInfo for exposed `assign_core` call
- [ ] Add configurations:
  - [ ] No legacy cores
  - [ ] Two bulk cores: one idling, one for coretime itself (pre-assigned) (currently we recycled the on_demand_cores config - so set this to 2, to get 2 core time cores)

Then have Coretime chain assign another para to the unoccupied core and see the other parachain starting to produce blocks: Tada! First basic test passed and we go from there. 

# Later Phase

Next up, would likely be core time chain actually manipulating the core count, after we implemented `request_core_count`.

If we move system chains over, we should test that this works smoothly. Core number will likely change, which should not matter, but worth testing.

**Comment by eskimor** [comment]
We need to provide matching initial configurations for relay chain and core time chain.

**Comment by kamilsa** [comment]
@eskimor am I right that there no available coretime zombienet tests? We were curious to run them with Kagome

**Comment by bkchr** [comment]
There is one: https://github.com/paritytech/polkadot-sdk/pull/2867

I think we can also close this ticket now.
