### ISSUE TITLE
People Chain: Rococo

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot-sdk#2371]
Launch the People Chain on Rococo and test the migration plan.

- [x] Block calls to Identity pallet on the Relay Chain (done in #1814)
    - [x] On-chain (expected `v1_004_000`)
- [x] Merge runtimes (#2281)
- [x] Use locked chain state to generate genesis state (script: #2025)
    - Note: Deposits will be "migrated" to zero, as no balances will be in the People Chain at genesis. 
- [x] Generate Chain Spec
- [x] Collator Deployment (https://github.com/paritytech/devops/issues/2847) (@PierreBesson ?)
- [x] Tests (normal system stuff plus `reap_identity`) (@0xmovses)
- [x] Write script to call `reap_identity` on all accounts
    - [x] Run it on Rococo
- [x] Ensure all deposits were correctly migrated
- [x] Do it again on Westend

(Note: original draft plan with extra notes/comments [here](https://hackmd.io/wamTNpV4SXKIYHjaXikQXw?view).)
