### ISSUE TITLE
Tracking issue for adding `try_state` hook to all pallets. 

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#239]
This is the tracking issue to add the `try_state` hook to as many pallets as we can. 

This hook was added in https://github.com/paritytech/substrate/pull/10174. The idea is as follows: 

```rust
/// Execute some checks to ensure the internal state of a pallet is consistent.
///
/// Usually, these checks should check all of the invariants that are expected to be held on all of
/// the storage items of your pallet.
///
/// This hook should not alter any storage.
pub trait TryState<BlockNumber> {
	/// Execute the state checks.
	fn try_state(_: BlockNumber) -> Result<(), &'static str>;
}
```

So, the ideas is to focus on invariants that must always be held in a pallet. A native, yet important example of this is that in the balances pallet, iterating over all users should yield the correct total issuance. 

Next, we want all pallets to call their `try_state` after each test. This can easily be achieved with a helper function like: 

https://github.com/paritytech/substrate/blob/dd8a34775aab9b362a5cc7552d5603c2fe812f82/frame/nomination-pools/src/mock.rs#L335

```rust
pub fn build_and_execute(self, test: impl FnOnce() -> ()) {
	self.build().execute_with(|| {
		test();
		// run the try-state of all pallets after each test.  
		<Runtime as TryState>::try_state(_, TryStateSelect::All).unwrap();
	})
}
```

Here is a list of current FRAME pallets, just for the sake of reference. Many of them won't need a `try_state` hook though. 

- [ ] alliance
- [ ] assets
- [ ] atomic-swap
- [ ] aura
- [ ] authority-discovery
- [ ] authorship
- [ ] babe
- [x] bags-list
- [ ] balances
- [ ] beefy
- [ ] beefy-mmr
- [ ] bounties
- [ ] child-bounties
- [x] collective
- [ ] contracts
- [ ] conviction-voting
- [ ] democracy
- [x] election-provider-multi-phase
- [ ] election-provider-support
- [ ] elections-phragmen
- [ ] examples
- [ ] fast-unstake
- [ ] gilt
- [ ] grandpa
- [ ] identity
- [ ] im-online
- [ ] indices
- [ ] lottery
- [ ] membership
- [ ] merkle-mountain-range
- [ ] message-queue https://github.com/paritytech/substrate/issues/13115
- [ ] multisig
- [x] nicks
- [ ] node-authorization
- [x] nomination-pools
- [ ] offences
- [ ] preimage
- [ ] proxy
- [ ] randomness-collective-flip
- [ ] ranked-collective
- [ ] recovery
- [ ] referenda @Szegoo https://github.com/paritytech/substrate/pull/13949
- [ ] remark
- [ ] root-offences
- [ ] root-testing
- [ ] scheduler
- [ ] scored-pool
- [ ] session
- [ ] society
- [x] staking
- [ ] state-trie-migration
- [ ] sudo
- [ ] support
- [ ] system
- [x] timestamp
- [ ] tips @Doordashcon https://github.com/paritytech/substrate/pull/13515
- [ ] transaction-payment
- [ ] transaction-storage
- [ ] treasury
- [ ] uniques
- [x] utility
- [ ] vesting @Doordashcon https://github.com/paritytech/substrate/pull/13515
- [ ] whitelist

Implementing this hook will allow these checks to be called in `try-runtime-cli`, and other testing tools that compile a runtime with `feature = try-runtime`. 

Note that for those who want to tackle a particular pallet, you must for sure deeply understand a pallet in order to correctly identify its list of invariants. Moreover, you might do your future generation a favor by documenting the invariants as good as you can.

**Comment by ayushmishra2005** [comment]
Recovery implemented here https://github.com/paritytech/polkadot-sdk/pull/5290

**Comment by rainbow-promise** [comment]
is the asset-conversion pallet part of this list? @kianenigma

**Comment by kianenigma** [comment]
All pallets with non-trivial logic are.

**Comment by nmammeri** [comment]
I like the idea of being able to call the try-state logic from unit tests. However, it looks like there is a lot of code duplication when implementing this for all the pallets. Why not have a  `DoTryState` trait or something that will enable us to not repeat the same the testing for all pallets. 
Many thanks

**Comment by kianenigma** [comment]
> I like the idea of being able to call the try-state logic from unit tests. However, it looks like there is a lot of code duplication when implementing this for all the pallets. Why not have a `DoTryState` trait or something that will enable us to not repeat the same testing logic for all pallets. Many thanks

Can you give an example of what `DoTryState` looks like and how it would remove duplicate code? Thanks!

**Comment by Krayt78** [comment]
This is an old issue but i guess its still usefull ? 
if so i might try some

**Comment by kianenigma** [comment]
If you find a useful case where a pallet should have invariants, but it doesn't, yes.
