### ISSUE TITLE
Extrinsic Vision

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot-sdk#2415]
Deprecate the terminology of "Unsigned" when used for transactions/extrinsics owing to there now being "proper" unsigned transactions which obey the extension framework and "old-style" unsigned which do not. Instead we have "general" for the former and "bare" for the latter. Ultimately, the latter will be phased out as a type of transaction, and bare will only be used for inherents.

We deprecate `ValidateUnsigned` and its associated namesakes.

All extrinsics are now validated either by `ProvideInherent` (which is an aggregated type of the runtime) or `TransactionExtension` (which is an explicitly configured type of the runtime).

Types of extrinsic are now therefore:
- Bare (no hardcoded signature, no Extra data; used to be known as "Unsigned")
  - Bare transactions (DEPRECATED): Gossiped, validated with `ValidateUnsigned` (DEPRECATED) and the `_unsigned` bits of `TransactionExtension` (DEPRECATED).
  - Inherents: Not gossiped, validated with `ProvideInherent`.
- Extended (with a TxExtension (ne Extra) data): Gossiped, validated via `TransactionExtension` type.
  - Signed transactions (with a hardcoded signature).
  - General transactions (without a hardcoded signature).

Once Bare transactions have been removed, "Extended transactions" will be synonymous with "transactions" and we don't bother with the "Extended" nomenclature. Similarly, "Bare extrinsics" will be synonymous with "Inherents" and we will drop the "Bare" nomenclature.

Three transaction version discriminators ("versions") are now permissible:
- 0b000000100: Bare (used to be called "Unsigned"): contains neither a Signature nor Extension (i.e. Extra data). After Bare transactions are no longer supported, this will strictly identify Inherents only and will be renamed as such.
- 0b100000100: Old-school "Signed" Transaction: contains Signature and Extension (Extra data).
- 0b010000100: New-school "General" Transaction: contains Extension (Extra data), but no Signature.

For the New-school General Transaction, it becomes trivial for authors to publish extensions to the mechanism for authorizing an Origin, e.g. through new kinds of key-signing schemes, ZK proofs, pallet state, mutations over pre-authenticated origins or any combination of the above.

### Stage 1

- paritytech/polkadot-sdk#2160
- Introduce `CheckSignature` impl of `TransactionExtension` to ensure it's possible.
- Stop using `Extrinsic` as much as possible internally, just use concrete types in tests.

### Stage 2: Remove concept of Unsigned transactions:
- Bare extrinsics are always inherents
- *General Transactions* exist to replace Unsigned transactions, but they are not bare - they have extensions.
- [ ] Check logic which determines whether an extrinsic is inherent or not...
- [ ] Deprecate `ValidateUnsigned` & `#[validate_unsigned]` (logic should be moved to `TransactionExtension`).
- [ ] Remove or migrate uses of `validate_unsigned`:
  - [ ] Frontier: migrate.
  - [ ] Claims: remove.

### Stage 2.5: Integrated semantic description
Transactions should include a metadata extension `VerifyMetadata`
- Extension places optional hash in the signed payload which corresponds to the hash of the metadata for the chain.
- Online signers simply hash the metadata and place it in the transaction.
- Offline signers should generally be provided with witness data to be able to construct a sparse Merkle tree of the metadata and display the transactions meaning to the user at the time of signing.

### Stage 3 PR: New APIs, deprecate old-school.
- Stop using and deprecate old items in `Extrinsic` trait.
- Introduce new `CreateTransaction` traits, simplifying transaction creation for tests & OCW.
  - `fn createTransaction(from: Signer, call: Call) -> UncheckedExtrinsic`;
    - called inside a state-queryable environment (so pallet storage can be gotten).
  - Implementing this is the requirement of the runtime, but can be mostly automated with utility structs.
- Deprecate `SignaturePayload`, `Extrinsic`, `CreateSignedTransaction`.
- Remove old test transactions and just use the regular `CheckedExtrinsic` and `UncheckedExtrinsic`.
- Remove `ExtrinsicWrapper`.
- Remove `ValidateUnsigned` and `#[validate_unsigned]`; bare extrinsics are always inherents and therefore always fail validation/pre-dispatch in `UncheckedExtrinsic`.

### Stage 3 PR: Remove old-school.
- Remove `SignaturePayload`, `Extrinsic`, `CreateSignedTransaction`.

**Comment by bkchr** [comment]
> Transactions should include a metadata extension `VerifyMetadata`

Wouldn't this also not just be a `TransactionExtension`?

**Comment by ggwpez** [comment]
>Remove or migrate uses of validate_unsigned:
  Frontier: migrate.
  Claims: remove.

What is the criteria for migration vs removal in the other pallets that use it?

**Comment by gavofyork** [comment]
If the transactions are not being used, then they can be deprecated and removed. But since `claim` was actually used only 5 days ago last, I guess we ought to keep it around 😕.

**Comment by bkchr** [comment]
We should also change `SignedPayload` to just always [hash the data that we sign/verify](https://github.com/paritytech/polkadot-sdk/blob/3e4e8c0bd1b1487c47c95dc27f2fff9e2f4e7fa0/substrate/primitives/runtime/src/generic/unchecked_extrinsic.rs#L254-L260). I don't really see the advantage of doing it this way.

**Comment by bkchr** [comment]
```
	fn validate(
		&self,
		origin: OriginOf<Call>,
		call: &Call,
		info: &DispatchInfoOf<Call>,
		len: usize,
		context: &mut Context,
		self_implicit: Self::Implicit,
		inherited_implication: &impl Encode,
	) -> ValidateResult<Self::Val, Call>;

	pub type ValidateResult<Val, Call> =
		Result<(ValidTransaction, Val, OriginOf<Call>), TransactionValidityError>;
```

Instead of this, I think it would be better to change the interface to:

```
	fn validate(
		&self,
		origin: Option<OriginOf<Call>>,
                signer: Option<Account>,
		call: &Call,
		info: &DispatchInfoOf<Call>,
		len: usize,
		context: &mut Context,
		self_implicit: Self::Implicit,
		inherited_implication: &impl Encode,
	) -> ValidateResult<Self::Val, Call>;

	pub type ValidateResult<Val, Call> =
		Result<(ValidTransaction, Val, Option<OriginOf<Call>>), TransactionValidityError>;
```

So, basically we would make the `origin` an `Option` and go back to passing the `signer`. This would bring us the advantage of chaining logic, but first let's look at the current structure. If I want to use the `SkipFeelessIf` with the `TransactionPayment` extension, I need to nest them. Aka `SkipFeelessIf<TransactionPayment>`. Now let's assume we actually want to have `General` transactions that are created by an offchain worker for example. The problem would be that we need to skip at least `TransactionPayment`. So, we would need to nest again `CustomExt<SkipFeelessIf<TransactionPayment>>>`. (We can probably continue this for multiple different extensions).

IMO it would be better to do this like:
```
Exts = (
     CustomExt,
     SkipFeelessIf,
     TransactionPayment,
);
```

At the beginning `origin` would be `None`. The extensions can set the `origin` to `Some`, which would signal the following extensions like `TransactionPayment` to not try to deduct any fees. If at the end of executing all extensions, `origin` would still be `None`, we would reject the transaction. This way we would also get back the old behavior of rejecting unsigned/general transactions "by default".

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/2024-04-23-technical-fellowship-opendev-call/7592/1

**Comment by gui1117** [comment]
> Now let's assume we actually want to have `General` transactions that are created by an offchain worker for example. The problem would be that we need to skip at least `TransactionPayment`. So, we would need to nest again `CustomExt<SkipFeelessIf<TransactionPayment>>>`. (We can probably continue this for multiple different extensions).

Maybe `TransactionPayment` should accept with no-op any origin which is not a signed origin.

`CustomExt` would transform the `None` origin into a pallet origin it relates to: `PalletA::Origin::OffchainOrigin`. And the triggered call would just ensure the origin is `PalletA::Origin::OffchainOrigin`.

This would allow different pipeline to be concurrent. Signed origin pipeline and `RuntimeOrigin::PalletA(PalletA::Origin::OffchainOrigin)` pipeline would be concurrent.

And we can have a `DenyNone` transaction extension as a final transaction extension. To avoid General Transaction to be able to call the deprecated unsigned transaction logics.

Alternatively we could also have some more complex pipeline structure with a top-level transaction extension which redirect to different pipeline depending on the call variant and the origin variant (signed or none).

Both seem doable with the current PR design.

**Comment by gui1117** [comment]
Now that transaction extension get a lot of custom logic, it could be great to be able to give custom error for invalid transaction.

There is `InvalidTransaction::Custom(u8)` but it is rather quite limited.

I think we should introduce the same variant as in `DispatchError`: `DispatchError::Module(ModuleError)`.

e.g.:
```diff
@@ -82,6 +83,8 @@ pub enum InvalidTransaction {
        MandatoryValidation,
        /// The sending address is disabled or known to be invalid.
        BadSigner,
+       /// A custom error in a module
+       Module(ModuleError),
 }
```

Then in the pallet we can just use the pallet error. It is already a type which cover multiple situation: the many different call of a pallet, so for the transaction extension situation, even if it is a different situation in nature, I think it is ok.

**Comment by bkchr** [comment]
> And we can have a `DenyNone` transaction extension as a final transaction extension. To avoid General Transaction to be able to call the deprecated unsigned transaction logics.

This sounds like a footgun. We should keep the logic that an unknown origin is rejected by default.

**Comment by georgepisaltu** [comment]
> an unknown origin is rejected by default

This can be implemented in the `Applyable::apply` and `Applyable::validate` logic of `UncheckedExtrinsic` by rejecting transactions without an origin when trying to dispatch the call.

However, we should provide a `DenyNone` extension as part of substrate because other implementers might be using transaction extensions but some other extrinsic type with a custom `Applyable` impl.

**Comment by bkchr** [comment]
> However, we should provide a `DenyNone` extension as part of substrate because other implementers might be using transaction extensions but some other extrinsic type with a custom `Applyable` impl.

I bet with you that they would never use this. This should be really not optional. Rejecting `None` should be the default. Then don't use `Option` to pass the origin and instead use a custom enum that can represent this.

**Comment by gui1117** [comment]
I agree we don't need `DenyNone` and we should make it by design.

I think we can make `CheckedExtrinsic` deny the `None` origin after the transaction extension checks.

So that bare extrinsic are dispatched with `None`,
and signed and general transactions are validated with transaction extension then if the returned origin is none it is invalid otherwise dispatched with the returned origin.

transaction extension is responsible to validate the transaction by giving it a sensible origin different from `None`.

**Comment by georgepisaltu** [comment]
I will implement the check in `Applyable::apply` and `Applyable::validate` logic of `CheckedExtrinsic` and add the necessary documentation around the trait to warn custom impls that they need to check the origin before call dispatch when applying extrinsics.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/introducing-transactionextension/10827/1

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/meta-transactions-support-for-polkadot/17551/12
