### ISSUE TITLE
META: FRAME Macro Ideas

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#264]
Let this be a collection of nice to have macros and attributes we should add to FRAME.

Where possible, link to bigger issues with more details.

- [ ] paritytech/polkadot-sdk#259
- [x] paritytech/substrate#10848
- [x] paritytech/substrate#13278
- [x] paritytech/substrate#13224
- [ ] paritytech/substrate#10762
- [x] paritytech/substrate#10251
- [ ] paritytech/substrate#9967
- [ ] paritytech/substrate#9493
- [ ] paritytech/substrate#9130
- [x] paritytech/substrate#8965
- [ ] paritytech/substrate#8803
- [ ] paritytech/substrate#3187
- [ ] paritytech/substrate#1441
- [ ] paritytech/polkadot-sdk#249
- [x] paritytech/substrate#13263
- [x] paritytech/substrate#12398
- [ ] paritytech/polkadot-sdk#213
- [ ] paritytech/substrate#6753
- [ ] paritytech/polkadot-sdk#205
