### ISSUE TITLE
Checks and Tools for the new release process

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#3046]
As https://github.com/paritytech/polkadot-sdk/pull/2490 is shaping up, now we can collect things that we will need for its implementation (please extend):

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-sdk/issues/3292
- [x] [CI] Prevent multiple version bumps of the same crate on master since the last stable release
- [x] [CI] Testing back-portability (whether a non-breaking change can be applied clean to `stable` and tests work)
- [x] Tool to figure out correct nightly and stable versions when bumping versions, tracked in https://github.com/liamaharon/cargo-workspace-version-tools/issues/1
- [x] Tool for clobbering, tracked https://github.com/liamaharon/cargo-workspace-version-tools/issues/1
- [x] Do a one-off sync with the versions of crates-io: https://github.com/paritytech/polkadot-sdk/pull/3034
```

**Comment by ggwpez** [comment]
Rough idea of this issue is done. More concrete follow up issues were created.
