### ISSUE TITLE
[xcm/pallet_xcm] New XCM version change improvements

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#3214]
## Summary

All the `xcm-builder` and `xcm-executor` modules are implemented with `xcm::latest::prelude::*` or `xcm::latest::*`. This means that when we add a new XCM version to the `xcm` module and change `latest` to point to the new XCM version, it affects everything.

One of the affected aspects is the XCM version handling in the `pallet_xcm`, where we store operational data with `XcmVersion` (e.g., [`SupportedVersion`](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/pallet-xcm/src/lib.rs#L631)). Currently, all data use `xcm::latest::XCM_VERSION` (e.g., [destination XCM versions](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/pallet-xcm/src/lib.rs#L1034)). The only way to migrate these data is to set [`CurrentMigration::<T>::put(VersionMigrationStage::default());`](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/pallet-xcm/src/migration.rs#L46), but this **is not used anywhere**, only in the old migration, which is not used.

One consequence is that the "notify subscribers when the XCM version changes" feature does not work without proper migration. Yes, we have `force_xcm_version` or `fn wrap_version` with `fn note_unknown_version` (we have one scenario for bridges where we don't use `wrap_version + note_unknown_version`, because `SubscribeVersion` does not work over bridge - [issue](https://github.com/paritytech/polkadot-sdk/issues/2417)), which could help and/or trigger negotiation from scratch, but then the "version notify" and `SubscribeVersion` become somewhat useless.

We didn't encounter this issue with XCMv3 because a migration was added to the runtimes [here](https://github.com/paritytech/polkadot/pull/4097/files#diff-db5840c3c03c740de25aed56b9257559c224a04619c079c94cddbb23f9a855a4R1500-R1501).

### Example of problem/issue

We encountered this issue on `BridgeHubRococo`. However, when we upgrade all testnet runtimes to version `1.7.0`, the problem will persist across all instances. In our case, we stored some XCM versions in `SupportedVersion` with `XcmVersion=3`. The `BridgeHubRococo` was subsequently upgraded with runtime versions featuring `XCMv4`, without any associated migration process. As a result, `pallet_xcm` now uses `XCM_VERSION=4` as a key to operational data, but no data were migrated to `XcmVersion=4`. This has led to the malfunctioning of certain functionalities. Unfortunately, there is currently no mechanism to trigger the migration; it can only occur with another runtime upgrade that includes the necessary migration steps.

## TODO/Improvements (minimal)

- [ ] Implement the `fn try_state` function in `pallet_xcm` to verify that all stored operational data has been migrated to the current XCM version, ensuring migration steps are not overlooked.
- [ ] Add reusable `MigrateTo(XcmVersion)` to the `pallet_xcm` - whenever the XCM version is updated, include the corresponding migration step `MigrateTo(XcmVersion::4)` in the runtime. After the upgrade, these migration steps can be removed.

## Improvements (other possibilities)
_(Maybe over-complicated and improvements (minimal) above are enough)_
- [ ] Avoid direct usage of `XCM_VERSION` in `pallet_xcm`. Instead, create a new storage item or reuse `pub const CurrentXcmVersion` as `pub storage CurrentXcmVersion`. This approach ensures that any changes to `XCM_VERSION` won't require automatic migration by default, preventing potential disruptions. Migrations will only be necessary if a runtime chooses to upgrade to a higher version, at which point they can add the corresponding migration step or trigger an extrinsic. Note: This approach may result in additional storage reads.
  - [ ] Introduce an extrinsic that allows manual triggering to initiate `CurrentMigration`.
- [ ] Explore other sophisticated solutions for adding new XCM version to the runtime. (Maybe without need to add/remove `MigrateTo(XcmVersion)`)
- [ ] Change storage version when upgrading to new XCM version? (That could force us to add migration)
