### ISSUE TITLE
Tokens Horizon

### ISSUE THREAD

**Issue by gavofyork** [paritytech/polkadot-sdk#327]
FTs:
- [x] `fungible::*` traits (#8435).
- [x] Implement `fungibles::Unbalanced` for `Assets` pallet (#8435).
- [x] Implement `fungible::*` for Balances pallet (#8454).
- [x] paritytech/substrate#12951 
- [ ] paritytech/polkadot-sdk#225
- [ ] FRAME: Make `Currency` trait an optional feature.
- [ ] FRAME: Introduce a default-off Config trait item in System allowing accounts to remain with no provider refs. (Requires https://github.com/paritytech/substrate/pull/13454)
- [ ] paritytech/polkadot-sdk#226
- [ ] paritytech/polkadot-sdk#228
- [ ] Introduce `AssetsFreezer` and `AssetsHolder` pallets and implement `fungibles::hold::*` and `fungibles::freeze::*` (https://github.com/paritytech/substrate/pull/8476)
- [ ] Introduce Provider pallet, which allows valuable assets to be locked in exchange for a provider reference.
- [ ] XCM for `can_withdraw`, `can_deposit`, `balance`, `reserved_balance`.
- [ ] Introduce `LockableAssets` derivative pallet and implement `fungibles::freeze::*`.

NFTs:
- [x] Uniques pallet (https://github.com/paritytech/substrate/pull/8813).
- [x] `nonfungible::*` traits (https://github.com/paritytech/substrate/pull/8993).
- [x] Implement `nonfungibles::*` for Uniques (https://github.com/paritytech/substrate/pull/8993).
- [x] XCM adaptors for `nonfungible::*` implementers.
- [ ] paritytech/polkadot-sdk#224
- [ ] Implement `nonfungible::*` trait for existing ownership systems that allow some transferable permission (membership of TC/Council, asset class ownership, ...).
- [ ] Create new type of pure Proxy with single transferable owner and implement `nonfungible::*` for it.

Associated paritytech/substrate#8285

**Comment by pandres95** [comment]
> * Introduce `AssetsFreezer` and `AssetsHolder` pallets and implement `fungibles::hold::*` and `fungibles::freeze::*` ([FRAME: Assets Freezer pallet substrate#8476](https://github.com/paritytech/substrate/pull/8476))

@gavofyork this is already completed by #3951 and #4530
