### ISSUE TITLE
[Assets] Implement `fungibles::freeze::Mutate`

### ISSUE THREAD

**Issue by pandres95** [paritytech/polkadot-sdk#3342]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

Locks are currently implemented on [`Balances`][docs:Balances_impl_MutateFreeze] due to the needs for existing use cases (e.g. [`pallet-staking`][docs:pallet-staking], [`pallet-conviction-voting`][docs:pallet-conviction-voting], etc.). 

However, over time, similar or novel use cases have been arising where locks are needed to be implemented on [`Assets` ][docs:pallet-assets]

One example of that is [Multi-governance on `pallet-communities`][link:communities_multiGov], where communities have an OpenGov-like system enabled, for which `AssetBalance` is a voting option. In this case, the balance of the asset used to vote from a user needs to be locked to prevent an account from voting using such balance, and then sending it over to another member, thus altering the poll results.

### Request

Implement `fungibles::MutateFreeze` for `pallet-assets`.

### Solution

Due to the current design of `pallet-assets`, there are two options (so, I open this issue to discuss the best course of action):

1. Create a pallet extension (conveniently called `pallet-assets-freezer`) that implements both [`FrozenBalance`][docs:FrozenBalance] (the trait described in [`T::Freezer`][docs::assets_Config] within `pallet-assets`) and [`fungibles::freeze::Mutate`][docs:MutateFreeze].
2. Replace `T::Freezer` with a proper implementation of [`fungibles::freeze::Mutate`][docs:MutateFreeze] within `pallet-assets`.

### Are you willing to help with this request?

Yes! (Of, course, assign it to me).

```[tasklist]
### Tasks
- [x] Define whether to implement as a pallet extension or within the pallet.
- [x] Propose `pallet-assets-freezer` extension.
```

[docs:Balances_impl_MutateFreeze]: https://docs.rs/pallet-balances/latest/pallet_balances/pallet/struct.Pallet.html#impl-MutateFreeze%3C%3CT+as+Config%3E::AccountId%3E-for-Pallet%3CT,+I%3E
[docs:pallet-staking]: https://docs.rs/pallet-staking
[docs:pallet-conviction-voting]: https://docs.rs/pallet-conviction-voting
[docs:pallet-assets]: https://docs.rs/pallet-assets
[link:communities_multiGov]: https://github.com/orgs/virto-network/projects/11?pane=issue&itemId=40980808

[docs:FrozenBalance]: https://docs.rs/pallet-assets/30.0.0/pallet_assets/trait.FrozenBalance.html
[docs::assets_Config]: https://docs.rs/pallet-assets/latest/pallet_assets/pallet/trait.Config.html
[docs:MutateFreeze]: https://docs.rs/frame-support/29.0.0/frame_support/traits/tokens/fungible/freeze/trait.Mutate.html

**Comment by pandres95** [comment]
According to @gavofyork's [response on OpenCall](https://youtu.be/bqLujRSs6iY?t=5460), the best course of action is not to implement `MutateFreeze` directly in `pallet-assets` in order to maintain the minimal necessary logic of it.

In consequence, it's best proceeding with the first option:

* Create a pallet extension (conveniently called `pallet-assets-freezer`) that implements both [FrozenBalance](https://docs.rs/pallet-assets/30.0.0/pallet_assets/trait.FrozenBalance.html) (the trait described in [`T::Freezer`](https://docs.rs/pallet-assets/latest/pallet_assets/pallet/trait.Config.html) within pallet-assets) and [`fungibles::freeze::Mutate`](https://docs.rs/frame-support/29.0.0/frame_support/traits/tokens/fungible/freeze/trait.Mutate.html).

Since there's a potential for a pallet extension, are there any public calls that might work on it?

**Comment by JelliedOwl** [comment]
Thank you for raising this - I suspect it's something I would want to use.  Sadly, I suspect my other issue with assets needs a separate solution.  https://github.com/paritytech/polkadot-sdk/issues/3451

**Comment by JelliedOwl** [comment]
Is what you're proposing more akin to locking (part of a balance) rather than freezing (all of an asset)? In which case, should it be called `pallet-assets-locker` instead?

Or I might be misinterpreting the intent of your issue.

**Comment by pandres95** [comment]
It is, makes sense to call it an `assets-locker` as this is the concept that's historically been used to refer to freezes (consider calling them Freezes instead of Locks is [fairly _recent_](https://github.com/paritytech/polkadot-sdk/issues/226)).

**Comment by JelliedOwl** [comment]
Thanks Pablo

I suspect I'll end up with an extension pallet to do the [Multi-asset Locking](https://github.com/paritytech/polkadot-sdk/issues/3451), which will interact with yours - but yours is probably more likely to be widely used so the interfacing and testing / maintaining should probably by my pallet's responsibility.  I suspect Parity isn't going to jump at taking on maintaining it for me.

There might be too much cross-interaction for my pallet to be just an extension anyway, so I might end up having to fork `pallet-assets`, which I'd really like to avoid.  

For example, I need account-frozen assets which are frozen by my multi-asset freezer not to be able to call the unlock function on those assets. (That possibly applies to assets frozen from the regular pallet_assets too, so you might need to handle that bit, at least). Hopefully that makes sense...

**Comment by liamaharon** [comment]
Any update on this @pandres95? It's needed for https://github.com/paritytech/polkadot-sdk/issues/3149, happy to provide any help you may need getting it moving.

**Comment by liamaharon** [comment]
Also want to mention this PR https://github.com/paritytech/substrate/pull/8476 here. The solution for this issue should probably follow it closely.
