### ISSUE TITLE
[pallet-xcm / pallet-xcm-benchmarks] Improvements

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#3470]
Relates to: https://github.com/paritytech/polkadot-sdk/pull/3464

## TODO

- [ ] remove usage `Currency` trait from `pallet-xcm` / `pallet-xcm-benchmarks`
- [ ] remove usage of  `pallet_balances` from benchmarks and replace with something generic e.g. `AssetTransactor` or `pallet-xcm-benchmarks` uses `type TransactAsset: frame_support::traits::fungible::Mutate<Self::AccountId>`
- [ ] `pallet_xcm` change `Currency` trait to `fungible` see `type Currency: LockableCurrency`
- [ ] fix `// TODO: correct weights.` in `on_initialize` for `VersionDiscoveryQueue`
- [ ] check `set_up_complex_asset_transfer` and `DeliveryHelper`
- [ ] move `xcm_sender` stuff from `polkadot-runtime-common` somewhere else (and then remove dependency from `parachain-system`)
- [ ] do not use `ED` as a transferable amount, better some "random" value
- [ ] return back verify for `teleport_assets` which was removed here https://github.com/paritytech/polkadot-sdk/pull/3455

**Comment by bkontur** [comment]
- [ ] more issues to check here: https://github.com/paritytech/polkadot-sdk/issues/900
