### ISSUE TITLE
Deprecation tracking issue for pallet-xcm `execute` and `send`

### ISSUE THREAD

**Issue by franciscoaguirre** [paritytech/polkadot-sdk#3771]
- [x] Deprecate code by adding a warning message -> https://github.com/paritytech/polkadot-sdk/pull/3749
- [ ] Remove usage of the deprecated code in the code base
- [ ] Update examples and tutorials
- [ ] Announce code deprecation
- [ ] Plan removal version
- [ ] Announce code removal
- [ ] Remove deprecated code

**Comment by xlc** [comment]
Could you explain a bit more why this is necessary and if there are anything that parachain teams should be aware of so that we can check our pallets to see if similar changes are needed?

**Comment by xlc** [comment]
I would like to get this out to reduce the impact to DX https://github.com/paritytech/polkadot-sdk/issues/4092
