### ISSUE TITLE
[FRAME core] ☂ Benchmark syntax V2 follow-ups

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#380]
After https://github.com/paritytech/substrate/pull/12924 is done, some things to consider (cc @sam0x17):  
- [ ] Remove code duplication with old macro expansion code.
- [x] paritytech/substrate#13235
- [x] ~#13277~
- [x] paritytech/substrate#13278
- [x] paritytech/substrate#13303
- [x] paritytech/substrate#13224
- [x] paritytech/substrate#13721
- [x] paritytech/polkadot-sdk#205
- [x] https://github.com/paritytech/polkadot-sdk/issues/376
- [ ] Testing
  - [x] Migrate more pallets so we can be sure that we cover everything with the new syntax.
  - [ ] Check for helpful error messages, maybe add help/tutorial links.
  - [x] Pallet UI tests, especially if we add new V2-only syntax.
- [ ] In-code docs
  - [x] paritytech/substrate#13383
  - [ ] Carrying over benchmark comments into the metadata and output them into the `WeightInfo` trait.
  - [ ] Expose benchmark functions to rust doc. I don think there is a good way of doing this though, since we want them private… maybe having a `benchmarks::doc` crate which only contains the docs could work.
- [ ] Syntax extensions
  - [ ] Try if the `#[must_use]` can work by using Clippy https://github.com/paritytech/polkadot-sdk/issues/285 or manually.
  - [ ] Modern version of `impl_benchmark_test_suite!`.
  - [ ] Consider multi-char component names
  - [x] Add `#[pov_mode]` attribute from https://github.com/paritytech/substrate/pull/11637
- [ ] External docs
  - [x] Either extend `pallet-basic-examples` or create a new examples pallet to show off **all** the V2 syntax as reference.
  - [ ] Check all README docs, substrate docs and docs.rs stuff
  - [ ] Update Tutorials
- [ ] Announce to Community (should do this once we are sure not to have breaking syntax changes)

**Comment by ggwpez** [comment]
The last two important issue to be feature complete have been done now. Going to close and otherwise re-open smaller issues.
