### ISSUE TITLE
[parachain-template] refactor for Enhanced Modularity to avoid `"God file pattern"`

### ISSUE THREAD

**Issue by asiniscalchi** [paritytech/polkadot-sdk#3819]
**As a** Parachain Developer,
**I want** to refactor the parachain-template runtime into a more modular structure,
**So that** new developers ( and me )  can easily understand and utilize the template, reinforcing the template's role in demonstrating best practices in blockchain development.

## Acceptance Criteria

1. **Modular Architecture**: The runtime must be divided into clear, logical modules that encapsulate specific functionalities. 

2. **Best Practices Showcase**: The refactoring must adhere to current best practices in software development, particularly those relevant to Rust and blockchain development. 

3. **Ease of Use**: The refactored codebase should make it easy for new developers to start using the template without the need for extensive guidance from existing contributors.

---
 
 Given the existence of a "god file" with more than 700 lines within Substrate's parachain template node—resulting in runtimes that extend beyond 2000 lines across the ecosystem—there's a recognized need for structural improvement. 
This refactoring initiative, while not directly impacting functionality, is intended to cater to the users of the parachain template node by improving its utility as both an exemplar and a foundation for new parachains. 
Additionally, this effort will help to **reveal SDK challenges that hinder the development of structured runtimes**.

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-sdk/pull/3817
- [ ] https://github.com/paritytech/polkadot-sdk/pull/3809
- [ ] https://github.com/paritytech/polkadot-sdk/pull/3818
```

**Comment by asiniscalchi** [comment]
https://github.com/paritytech/polkadot-sdk/pull/3809
https://github.com/paritytech/polkadot-sdk/pull/3817
https://github.com/paritytech/polkadot-sdk/pull/3818
-----
https://github.com/paritytech/polkadot-sdk/pull/3804 <--- just for historical monitoring

**Comment by asiniscalchi** [comment]
something is moving ... https://github.com/paritytech/polkadot-sdk/issues/3916

**Comment by kianenigma** [comment]
I am not against such syntactic improvements in general and appreciate the effort. 

What I dislike about this is that it is drifting our templates even further apart. If any change is applied to any template, it should be standardized in all templates under `/template`.

**Comment by asiniscalchi** [comment]
Let's create a couple of user story to adapt the other templates to the new structure as soon as we are happy with the result.
