### ISSUE TITLE
Benchmark Weight Assumptions

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#393]
The following hard coded weights should be automatically generated:
- [x]  `ParityDbWeight, RocksDbWeight`: time to access storage items paritytech/substrate#10897
- [x] Optional: DB benchmarking for `RocksDB`+`ParityDB` -> Does not belong to Substrate
- [x] `BlockExecutionWeight`: time to import an empty block paritytech/substrate#10977
- [x] `ExtrinsicBaseWeight`: time to execute a no-op extrinsic (`System::remark`) paritytech/substrate#10977  
- [x] Add a way to compare historic block weights to their consumed time paritytech/substrate#11091
- [ ] Further we want to measure the throughput of Substrate nodes. Formerly this yielded ~1,500 etx/s. paritytech/substrate#10720
- [ ] Remove `constants` module from weight templates
