### ISSUE TITLE
Benchmarking Roadmap 2022 (Tracking Issue)

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#397]
In 2022, we should prioritize the next wave of benchmarking and optimization for Substrate / Polkadot.

## Goals

* improve transaction density / throughput in blocks.
* improve developer quality of life for benchmarks.
* improve story specifically in the context of weights for parachains.

## Developer Quality of Life

- [x] paritytech/substrate#10848
- [x] Improve `list_benchmark`, `add_benchmark` to remove redundancy and manual management (maybe a meta macro for the definition) in https://github.com/paritytech/substrate/pull/10592
- [ ] Add a flag to FRAME storage for "keeping a storage in memory" from block to block, automatically populates whitelist, and remove the need for manual whitelist declaration.
- [ ] Better handle pallets with multiple instances and how we run and output their files.

## Improve Throughput

- [x] Switch from RocksDB to ParityDB (Q1 2022)
- [x] Reassess previous assumptions (block overhead, transaction overhead, etc...)
- [x]  New reference hardware for benchmarking the runtime. https://github.com/w3f/polkadot-wiki/pull/3564
    - [x] Rerun benchmarks for this hardware.
    - [ ] Migration plan for community to switch to this hardware.
- [ ] Investigate the use of OS specific optimized binary
- [ ] Look at existing performance / benchmarking tools in the RUST ecosystem

## Improve Accuracy

- [ ] Complete work for PoV benchmarking. https://github.com/paritytech/substrate/issues/8652
- [ ] Track memory read / writes in addition to DB read / writes.
- [ ] Dual weight limits for Collators on Parachain Network and Validators on Polkadot Network
    - [ ] Remove DB reads / writes for validator blocks (use memory reads / writes instead)
- [ ] Dynamic Storage Weights (measuring DB reads / writes impact dynamically based on worst case encoding size)

**Comment by vedhavyas** [comment]
@shawntabrizi checking if there has been any change to reference hardware used to benchmark the runtime is still the same - https://github.com/w3f/polkadot-wiki/pull/3564

if not, can you point me to the latest reference pls?

**Comment by shawntabrizi** [comment]
@ggwpez should know

**Comment by vedhavyas** [comment]
@ggwpez wondering if you can confirm the current hardware reference used for benchmarking runtime

**Comment by ggwpez** [comment]
It is described in the [polkadot-wiki](https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#standard-hardware).  
For updating the weights we use some Google server with Intel Ice Lake CPU series. The weights come in very consistent so far.
