### ISSUE TITLE
PoV Benchmarking Tracking Issue

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/polkadot-sdk#398]
This is a meta issue to track the things needed to add benchmarking support for PoV size, critical for launching Parachains on Polkadot.

- [x] Enable Measurement of PoV Size in Benchmarking Pipeline https://github.com/paritytech/substrate/pull/8559
- [ ] Take into account PoV compression
- [x] Add `MaxEncodedLen` requirement to storage (meta issue: https://github.com/paritytech/substrate/issues/8719) https://github.com/paritytech/substrate/pull/8735
- [x] Add `BoundedVec` to Storage Primitives https://github.com/paritytech/substrate/pull/8556
- [ ] Migrate existing storage `Vec` to `BoundedVec` (meta issue: https://github.com/paritytech/polkadot-sdk/issues/323)
- [x] Measure average PoV overhead for storage Maps
- [ ] Re-evaluate benchmarks for worst case PoV conditions
- [x] Weight Tuple `(computation_weight, pov_weight)` and abstractions https://github.com/paritytech/polkadot-sdk/issues/256
- [x] Weight Output Generation / Automation
