### ISSUE TITLE
Deprecation tracking issue for XCMv2

### ISSUE THREAD

**Issue by franciscoaguirre** [paritytech/polkadot-sdk#4125]
- [ ] Deprecate code by adding a warning message
- [ ] Remove usage of the deprecated code in the code base
- [ ] Update examples and tutorials
- [ ] Announce code deprecation
- [ ] Plan removal version
- [ ] Announce code removal
- [ ] Remove deprecated code
