### ISSUE TITLE
[Tracker] Add runtime apis to Kusama and Polkadot runtime

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#4313]
Tracker issue to add Staking runtime apis to fellowship runtimes Kusama and Polkadot.
- [ ] pending_rewards (https://github.com/paritytech/polkadot-sdk/pull/4301).
- [ ] eras_stakers_page_count.
- [ ] Ideal staking rate.
