### ISSUE TITLE
Define and implement `Hold` for Assets

### ISSUE THREAD

**Issue by pandres95** [paritytech/polkadot-sdk#4315]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

A follow-up of #3342. The current design of `pallet-assets` doesn't implement holds, while there are multiple use cases for which it would be beneficial to support this behaviour (e.g. bonding, staking, deposits, payment holds, escrowed vesting, etc.).

### Request

Because of the above, it is desirable to find a way of implementing inspection and mutation of the [`fungibles::holds`]() traits.

### Solution

- [x] #4530

A basic definition and implementation of a `HeldBalance` (an analogous to `FrozenBalance`) that can be added as a type in `pallet-assets`.

```rs
pub trait HeldBalance<AssetId, AccountId, Balance> {
    // Required methods
    fn held_balance(asset: AssetId, who: &AccountId) -> Option<Balance>;
    fn died(asset: AssetId, who: &AccountId);
}
```

Then, by using the `held_balance` method in Assets, it would be possible to subtract the free balance to obtain the `reducible_balance`, and adjust to the [balance components](https://paritytech.github.io/polkadot-sdk/master/frame_support/traits/tokens/fungible/index.html#visualising-balance-components-together-) model.

Analogous to `pallet-assets-freezer`, this proposed pallet extends the capabilities of `pallet-assets` to support holding balances.

### Are you willing to help with this request?

Yes!

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-sdk/pull/4530
```

**Comment by pandres95** [comment]
Quick question before proceeding with the proposed implementation: after taking a review on #236, I noticed that (at least for `fungible` tokens) it is expected that holds are not overlapped with free balance, while frozen may be applied to the total balance (including `held` balances).

This leads me to think the `reducible_balance` for an asset account should be calculated as `total - max(frozen, held)`.

Is this assumption correct @gavofyork, or does this concept only for `fungible` tokens?

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/2024-05-21-technical-fellowship-opendev-call/8264/1

**Comment by muharem** [comment]
> Quick question before proceeding with the proposed implementation: after taking a review on #236, I noticed that (at least for `fungible` tokens) it is expected that holds are not overlapped with free balance, while frozen may be applied to the total balance (including `held` balances).
> 
> This leads me to think the `reducible_balance` for an asset account should be calculated as `total - max(frozen, held)`.
> 
> Is this assumption correct @gavofyork, or does this concept only for `fungible` tokens?

there is an issue explaining these relations. you should look for the PR introducing new fungible/s traits. should be linked there.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/assethub-new-feature-bond-with-specific-unbond-period/7494/3

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/2024-07-16-technical-fellowship-opendev-call/9512/1
