### ISSUE TITLE
Tracker issue for cleaning up old non-paged exposure logic in staking pallet

### ISSUE THREAD

**Issue by Ank4n** [paritytech/polkadot-sdk#433]
This issue is to track merging of https://github.com/paritytech/substrate/pull/13059 and subsequent release of paged rewards on Polkadot. Once enabled, and 84 eras have passed, we can clean up incremental migration and fallback logic from the staking pallet.

84 eras in Polkadot = 84 days.
Deprecated storage items can be cleaned from codebase on or after Era 1504 (approx: July 14, 2024) on Polkadot. 

### Track
- [x] Paged rewards enabled in Kusama on Era 6514 (Apr 18).
- [x] Paged rewards enabled in Polkadot on Era 1420 (Apr 21).

### Tasks
- [x] Remove storage item `ErasStakersClipped` and `ErasStakers`.
- [x] Remove fn `EraInfo::is_rewards_claimed_temp`.
- [x] Clean up logic around `StakingLedger.legacy_claimed_rewards`.
- [x] BoundedVec everything

Note on bounding:

I did not bound new paged storage items since the exposure page size would decrease in future which is unsafe for `bounded vecs`. Initially, page size would be 512 and page count = 1, but after running for a while, we should set the page size such that we don't see them reducing further. For example, when we clean up this ticket, we could then bound the page size to `32` and page count to `16`. From that point, we should strive to never reduce the page size and page count should only increase further.

**Comment by Ank4n** [comment]
Referenda for upgrade containing paged exposure:
- Kusama: https://kusama.polkassembly.io/referenda/373
- Polkadot: https://polkadot.polkassembly.io/referenda/648
