### ISSUE TITLE
Debug current script

### ISSUE THREAD

**Issue by EgorPopelyaev** [paritytech/polkadot-sdk#4393]
This is a main issue for the analysis and creation of the scripts or functions which can be taken over to the new release process flow.

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/release-engineering/issues/199
- [ ] https://github.com/paritytech/release-engineering/issues/201
- [x] Analize and prepare scripts which can be used in the new process
```

**Comment by EgorPopelyaev** [comment]
I went through the scripts we currently have to run a release, here is the list of those that are involved and might be re-used in the automation process:
Scripts from [`release-engineering`](https://github.com/paritytech/release-engineering) repo needed for the pipelines:

- Branch-off `stable` branch
    - Steps in the script:
        - set NODE_VERSION
        - set runtimes SPEC_VERSION
        - create `stable branch`
            - `prepare_brnachoff_base_branch`
            - `branchoff_release_branch`
            - `set_node_version`
            - `get_cumulus_cargo_toml_list` + `set_crate_versions`
            - `get_filtered_runtimes_list_for_repo` + `set_spec_versions`
            - `reorder_prdocs`

Scripts from [`cleanroom`](https://github.com/paritytech/cleanroom) needed for the pipelines:

- `polkadot-release-strategy`
    - Steps in the script:
        - get rc tag
        - checkout release rc tag
        - build binary
            - `container-run /scripts/build-linux-release.sh`  for `polkadot`, `polkadot-prepare-worker`, `polkadot-execute-worker`
        - build deb package
            - `container-run /scripts/build-deb.sh`
        - sign artifacts
        - upload to github (will be replaced by gha)
        - upload to s3 (probably will be replaced by gha)
- `cumulus-release-strategy`
    - Steps in the script:
        - get rc tag
        - checkout release rc tag
        - build binary
            - `container-run /scripts/build-linux-release.sh`  for polkadot-parachain
        - sign artifacts
        - upload to github (will be replaced by gha)
        - upload to s3 (probably will be replaced by gha)

Some part of those might be replaced by the GHA's in the pipelines directly. The implementation of those will be done as part of the tasks to build CI pipelines listed here: https://github.com/paritytech/release-engineering/issues/217
