### ISSUE TITLE
Improvements to `polkadot-sdk-frame` umbrella crate

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#4782]
- [ ] In the docs, explicitely mention the suggested use of `prelude` modules as the suggested way. Atm, this is not easily visibile [in the first example](frame_support::pallet_macros::call) that you would encounter, if you start digging into the crate docs.
- [ ] Provide proper erros for `#[cfg(not(feature = "experimental"))]` that, instead of not working, provide a compiler error that says the `frame` crate is experimental.

**Comment by kianenigma** [comment]
- [ ] Make `preludes` use-able: As in: I should be able to write a reasonable pallet + runtime + tests + benchmarks without needing to use anything other than `prelude::*` + `runtime::prelude::*` + `testing::prelude::*` + `benchmarking::prelude::*`. 
- [ ] Either remove the `experimental` flag, or document the issues that need to be removed before we remove it.

**Comment by shawntabrizi** [comment]
You are not exporting `TokenError`, and perhaps other `DispatchError` variants.

**Comment by AurevoirXavier** [comment]
I'd like to help migrate existing pallet if there is a list.

**Comment by kianenigma** [comment]
Yes there is: https://github.com/paritytech/polkadot-sdk/issues/6504

**Comment by ggwpez** [comment]
I think we removed the experimental flag now, so the only point remaining is the last one about docs.

**Comment by kianenigma** [comment]
- [ ] Logging and tracing functionality is missing

**Comment by ggwpez** [comment]
Yea seems sensible. Although we do mention both in the umbrella README now. But if you have something else to add, then please go ahead 😄
