### ISSUE TITLE
☂ Fix flaky tests

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#48]
Some tests just randomly fail in the CI.  

Known bad with last confirmation date:
- [ ] `follow_report_multiple_pruned_block` https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2540531
- [ ] `follow_forks_pruned_block` https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2529507
- [ ] `returns_status_for_pruned_blocks` https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2522151
- [ ] `can_sync_small_non_best_forks` https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2635997
- [ ] `telemetry_works` on commit 890451221db37176e13cb1a306246f02de80590a `assertion failed: self.wait().unwrap().success()` (see [comment](https://github.com/paritytech/polkadot-sdk/issues/48))
- [x] `beefy_reports_equivocations` [CI](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2945367) 2023-06-14 - fix https://github.com/paritytech/substrate/pull/14382
- [ ] `response_headers_invalid_call` [CI](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2906830) 2023-05-29
- [x] `ensure_parallel_execution`: `Expected duration 6697ms to be less than 6000ms` (2023-06-13) - fix paritytech/polkadot#7390
- [x] `execute_queue_doesnt_stall_with_varying_executor_params`: `Expected duration 12912ms to be less than or equal to 12000ms` (2023-06-13) - fix paritytech/polkadot#7390
- [ ] `sc-offchain api::http::tests::response_header_invalid_call` [CI log](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3005576) (2023-06-16)

Maybe flaky, maybe fixed :ghost::
- [ ] `running_the_node_works_and_can_be_interrupted` [error-log.txt](https://github.com/paritytech/substrate/files/8590101/error-log.txt) 8a9f48bcf0c9f92949082535d77c12166522bb2f  
- [ ] `notifications_back_pressure` https://github.com/paritytech/substrate/issues/9045

Fixed:
- [x] `temp_base_path_works` https://github.com/paritytech/substrate/pull/13505  [error-log.txt](https://github.com/paritytech/substrate/files/8590101/error-log.txt)
- [x] `subscribe_and_unsubscribe_to_justifications`
- [x] `syncs_header_only_forks` https://github.com/paritytech/substrate/issues/12607
- [x] babe `authoring_blocks` https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2101500 https://github.com/paritytech/substrate/pull/13199

**Comment by alvicsam** [comment]
I'd also add `sc-network discovery::tests::discovery_working` because It looks as if it sometimes just hangs: https://github.com/paritytech/polkadot-sdk/actions/runs/15180086844/job/42701594693

**Comment by alvicsam** [comment]
Also @kianenigma [mentioned](https://github.com/paritytech/polkadot-sdk/pull/8578#issuecomment-2898391667) these ones:

```
rejects_missing_seals
sync_to_tip_when_we_sync_together_with_multiple_peers
works_with_different_block_times  
```

**Comment by alvicsam** [comment]
<del>And another one: `sc-service-test client::returns_status_for_pruned_blocks` https://github.com/paritytech/polkadot-sdk/actions/runs/15187569760/job/42711817408</del> [fixed](https://github.com/paritytech/polkadot-sdk/issues/8689)

**Comment by alindima** [comment]
ensure_operation_limits_works: https://github.com/paritytech/polkadot-sdk/actions/runs/15294554712/job/43020843814#step:4:4001

**Comment by kianenigma** [comment]
A new one potentially found in https://github.com/paritytech/polkadot-sdk/actions/runs/19265662309/job/55081001166#step:4:5020:
