### ISSUE TITLE
[meta] strict on-runtime-upgrade CI checks to prevent accidental runtime upgrade breakages

### ISSUE THREAD

**Issue by liamaharon** [paritytech/polkadot-sdk#481]
`try-runtime-cli` `on-runtime-upgrade` has stabilised over the last few months to that point where we can add CI checks to ensure Polkadot & Substrate PRs don't accidentally break upcoming polkadot/kusama/rococo/westend runtime upgrades

Creating a meta issue to track this progress.

Remaining TODOs:
- [x] Fix existing migration issues
  - [x] https://github.com/paritytech/substrate/pull/14421
  - [x] https://github.com/paritytech/polkadot/pull/7454
- [x] Update polkadot CI to run on-runtime-upgrade on every polkadot PR https://github.com/paritytech/polkadot/pull/7422
- [x] Merge https://github.com/paritytech/substrate/pull/14311
- [ ] ~Implement `VersionedRuntimeUpgrade` for `Unreleased` pallet migrations~
- [x] Add a check to substrate CI that will fail if a companion needs to be written to prevent runtime migration breakage https://github.com/paritytech/substrate/pull/14618
- [x] Fix Polkadot HostConfiguration: https://polkadot.polkassembly.io/referenda/9

After some time has passed and we are confident in the robustness of the CI checks:
- [x] Block merging until on-runtime-upgrade checks are green https://github.com/paritytech/ci_cd/issues/785

**Comment by liamaharon** [comment]
Done
