### ISSUE TITLE
[FRAME] Remove Gov V1 from Polkadot and Kusama & unlock/unreserve funds

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#485]
_Originally posted by @kianenigma in https://github.com/paritytech/polkadot/pull/6701#discussion_r1103825551_
         

### Tasks
- [x] Merge migrations to unreserve & unlock funds from Gov V1 pallets 
    - [x] `elections-phragmen`: migration unreserving `Members`, `RunnerUps`, `Candidates`, and `Voters` `deposit`s and unlocking `Voter` `stakes`. 
        - https://github.com/paritytech/substrate/pull/14218
    - [x] `democracy`: migration unreserving all accs in `DepositOf` and unlock all `Voter` funds stored under this pallet.
        - https://github.com/paritytech/substrate/pull/14226
    - [x] `tips`: migration unreserving all `OpenTip`s 
        - https://github.com/paritytech/substrate/pull/14241
    - `collective`: balances migration not necessary
    - `membership`: balances migration not necessary
- [x] Create `RemovePallet` migration utility (https://github.com/paritytech/substrate/pull/13835)
- [x] Next Kusama runtime upgrade unreserve & unlock funds from all Gov V1 pallets 
    - https://github.com/paritytech/polkadot/pull/7314
- [x] Verify Kusama unreserve & unlock of all funds was successful 
- [x] Once pallets are no longer in the Kusama runtime, remove the storage with the RemoveStorage migration 
- [x] Next Polkadot runtime upgrade unreserve & unlock funds from all Gov V1 pallets
- [x] Verify Polkadot unreserve & unlock of all funds was successful
- [x] Once pallets are no longer in the Polkadot runtime, remove the storage with the RemoveStorage migration 
- [ ] Fully document the transition from Gov v1 -> Gov v2

### Unreserving / unlocking details

We need to unreserve / unlock all funds in the pallets before we delete the storage. 

more info from @kianenigma : 

> do a quick analysis of the code of these pallets and find all deposit instances within FRAME, every time we reserve a deposit, we alway store it somewhere in the storage of the pallet as well (namely because we only recently started to use named deposits, so it was hard to keep record). Example: https://github.com/paritytech/substrate/blob/master/frame/elections-phragmen/src/lib.rs#L154
>
> Then you can create some kind fake storage map for these maps (using #[storage_alist] macro), iterate the map, unreserve.
>
> For locks it is similar, but simpler because the locks are all stored in the balances pallet; you just need to recover the PalletId of all of these pallets, then call into Balances::remove_lock.

**Comment by liamaharon** [comment]
Migration guide published: https://forum.polkadot.network/t/gov-v1-to-opengov-a-technical-migration-guide/4116

**Comment by jam10o-new** [comment]
Heya.

I'm sitting on a Kusama account that still has a democracy lock on it. Not completely sure what's going on there, but it looks like many, many other accounts are affected. Somewhere to start looking around could be accounts with votes that were expired (ready to unlock) but not unlocked during the migration (ie, they would not be visible in VotingOf or DepositOf, the storage you checked in your migration, and just needed a simple call to democracy.unlock()), but I also notice some high-conviction votes that wouldn't have been expired at the time of migration with this issue, so it's probably not that simple. 

To illustrate the scale of this issue, you can go to any gov1 referendum:

 https://kusama.subscan.io/referenda
 
  and look through the voters. Almost all voters who have votes that are not labelled as expired also still have a democracy lock, but this is not a rule.  
  
  (for illustration, here's the final referendum: https://kusama.subscan.io/referenda/273, and the first voter you see there: https://kusama.subscan.io/account/D3Fh5td8SjuWn3GR7WEQyZx6TncxwFLaix2YTvygMyxDcU9, has a substantial lock still on their account. This can also be verified in the apps UI in case you don't trust block explorers for whatever reason)
  
  fwiw, I suspect that the reason why folks haven't been noticing this is because it primarily effects older members of the community and active or previously high conviction voters :upside_down_face: - our wallets and gov UI's generally automatically set vote sizes to the amount currently already locked for voting, so unless you stopped voting and let other locks expire like I have, you wouldn't notice that you have a permanent gov1 lock on your account.
  
I'm frankly not interested in participating in this community anymore tbqh, just want my tokens unlocked, so forgive me for not speaking up about/looking into this earlier, that's it for my free labor, good luck. :shrug:

**Comment by liamaharon** [comment]
Hey @jam10o-new, the runtimes have not been deployed yet, that is responsibility of the fellowship. Deployment can be tracked on their repo here: https://github.com/polkadot-fellows/runtimes/issues/20

**Comment by jam10o-new** [comment]
apologies.
