### ISSUE TITLE
Backport integration tests for claim assets to the `polkadot-sdk` from `polkadot-fellows` repo

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#4892]
Relates to: https://github.com/polkadot-fellows/runtimes/issues/363

## TODO

- [ ] backport [claim_assets test case](https://github.com/polkadot-fellows/runtimes/blob/main/integration-tests/emulated/tests/assets/asset-hub-kusama/src/tests/claim_assets.rs) to the `polkadot-sdk` testnet integration tests
- [ ] backport macro [`test_chain_can_claim_assets`](https://github.com/polkadot-fellows/runtimes/blob/main/integration-tests/emulated/helpers/src/lib.rs#L218) from fellows repo
- [ ] when merged to `polkadot-sdk` and released, make sure that it is propagated to the fellows repo: https://github.com/polkadot-fellows/runtimes/issues/363
- [ ] backport and align other macros/test-cases from https://github.com/polkadot-fellows/runtimes/blob/8ec28f96eeb30fbba30d29006d75e1a3fa1cea1c/integration-tests/emulated/helpers/src/lib.rs#L31-L33

**Comment by programskillforverification** [comment]
Can you assign this one to me?

**Comment by acatangiu** [comment]
This is done.
