### ISSUE TITLE
Deprecation tracking issue for `XcmFeeToAccount`

### ISSUE THREAD

**Issue by ozgunozerk** [paritytech/polkadot-sdk#4979]
- [ ] Deprecate code by adding a warning message -> https://github.com/paritytech/polkadot-sdk/pull/4959
- [ ] Remove usage of the deprecated code in the code base
- [ ] Update examples and tutorials
- [ ] Announce code deprecation
- [ ] Plan removal version
- [ ] Announce code removal
- [ ] Remove deprecated code
