### ISSUE TITLE
Elastic scaling: launch checklist

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-sdk#5051]
This is the list of tasks to be completed for launching elastic scaling on Polkadot: 
- [x] https://github.com/paritytech/polkadot-sdk/pull/6452
- [x] https://github.com/paritytech/polkadot-sdk/pull/6739
- [x] https://github.com/paritytech/polkadot-sdk/issues/6442
- [x] Release `stable2412` which includes runtime and node/collator side implementation of RFC103
- [x] https://github.com/paritytech/polkadot-sdk/pull/7254
- [x] `stable2503`: Stable Slot based collator 
- [x] [Referenda](https://kusama.subsquare.io/referenda/519) to enable RFC103 on Kusama
- [x] [Referenda](https://polkadot.subsquare.io/referenda/1546) to enable RFC103 on Polkadot
- [x] Kusama/Polkadot runtime upgrade to `stable2412`
- [x] https://github.com/paritytech/polkadot-sdk/pull/9967

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/elastic-scaling-wen-500ms-blocks/11971/11
