### ISSUE TITLE
Update polkadot CPU score to reflect 8 cores are minimum required

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#5122]
Full context of the discussion is here https://forum.polkadot.network/t/rfc-increasing-recommended-minimum-core-count-for-reference-hardware/8156, long story short the minimum required core count for validators need to be increased from 4 to 8 to increase the overall capacity for PVF execution, to fully take advantage of async backing.

The feedback from validators have been overwhelming positive, so as a first step we need to modify the CPU score benchmark to reflect this changes and inform validators at startup that in the future this will become the norm.

Note!! This should not do any enforcements at this moment it should be just to inform validator that they are not meeting this requirements and they need to take the necessary steps to increase their capacity.

## TODO
- [ ] https://github.com/paritytech/polkadot-sdk/pull/5127
- [ ] Referenda pases https://polkadot.subsquare.io/referenda/1051
- [x] Updatee wiki text to reflect this is coming  https://github.com/w3f/polkadot-wiki/pull/6202

**Comment by ggwpez** [comment]
Whatever you change, please keep the polkadot Wiki in sync: https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#reference-hardware

**Comment by alexggh** [comment]
> Whatever you change, please keep the polkadot Wiki in sync: https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#reference-hardware

Yes, definitely.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/rfc-increasing-recommended-minimum-core-count-for-reference-hardware/8156/10
