### ISSUE TITLE
Bunches of bug reports related to polkadot v1.13.0 version upgrade

### ISSUE THREAD

**Issue by chungquantin** [paritytech/polkadot-sdk#5213]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

After a few attempts to upgrade my parachain from `v1.12.0` to `v1.13.0` using `psvm -v 1.13.0` without any luck, I have seen a lot of bug reports on Substrate stack exchange. I think this is critical because the Polkadot SDK maintainer does not give a clear guideline on how to upgrade the parachain, while the parachain builders did not receive enough resources and technical support even on Substrate Stack Exchange. Here is the list of issues that need to be supported by the core engineers of the SDK: 
- 🚩 Not resolved: [use of undeclared crate or module `alloc` when upgrade to `v1.13.0`](https://substrate.stackexchange.com/questions/11786/use-of-undeclared-crate-or-module-alloc-when-upgrade-to-v1-13-0)
- Resolved: [frame-support cannot find vec when upgrade to SDK 1.13](https://substrate.stackexchange.com/questions/11781/frame-support-cannot-find-vec-when-upgrade-to-sdk-1-13)
- Resolved: [Unable to compile upgrade parachain node after running `psvm v1.13.0`](https://substrate.stackexchange.com/questions/11774/unable-to-compile-upgrade-parachain-node-after-running-psvm-v1-13-0)
- 🚩 Not resolved: [More errors after upgrade to SDK 1.13](https://substrate.stackexchange.com/questions/11793/more-errors-after-upgrade-to-sdk-1-13)

My recommendation is to have a Polkadot SDK version upgrade cookbook. We have seen the new release of Polkadot SDK brings a lot of breaking changes. And if the parachain team can't upgrade their parachain in time, there might be a chance that they can't fix the urgent bug on their parachain. 

### Steps to reproduce

Simply running `psvm -v 1.13.0` and you will find the bug right away. For more context, I upgraded my parachain from `v1.12.0`
```[tasklist]
### Tasks
- [x] frame-support cannot find vec when upgrade to SDK 1.13
- [ ] More errors after upgrade to SDK 1.13
- [ ] use of undeclared crate or module alloc when upgrade to v1.13.0
- [x] Unable to compile upgrade parachain node after running psvm v1.13.0
```

**Comment by xlc** [comment]
compiler isn’t bugs just saying….

**Comment by chungquantin** [comment]
@xlc I don't say that it needs to be 100% clean when upgrading but there is no clear documentation to guide builders what needs to fix.
