### ISSUE TITLE
Make `polkadot-sdk` templates OMNI and GREAT again -- part 2

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#5242]
> [!NOTE] 
> The follow-up to https://github.com/paritytech/polkadot-sdk/issues/3155, and a huge shoutout to @rzadp so far for his help.

Now we have a new system that syncs our 3 templates into 3 repos, every few weeks, all automatic, guaranteed to work. 

* https://github.com/paritytech/polkadot-sdk-minimal-template
* https://github.com/paritytech/polkadot-sdk-solochain-template
* https://github.com/paritytech/polkadot-sdk-parachain-template

The purpose of these 3 templates will be to **demonstrate all the latest features of polkadot-sdk**, and act as un-opinionated starting points. We expect other teams to build more opinionated templates, and feel free to add these to https://paritytech.github.io/polkadot-sdk/master/polkadot_sdk_docs/polkadot_sdk/templates/index.html

I have spread the word of what needs to be done to push the template revamp to full completion in the above issue, but the thread has gotten a bit unorganized by now. In this issue, I will re-iterate the action items. 

> [!TIP] 
> All of the work mentioned here is, in my opinion, high impact, and relatively simple. This means: great oppurtunity for both Parity and exteranl contributors! 

### Use `polkadot-sdk` and `polkadot-sdk-frame`

The entire template should mostly be 3 crates: `polkadot-sdk` plus, `codec` and `scale-info`. **For the case of `polkadot-sdk-frame`, please use `prelude::*`. If a prelude is missing something, open a PR and add it**. If there should be further preludes (e.g. `frame::benchmarking_prelude::*`?) please add one. 

- [ ] minimal https://github.com/paritytech/polkadot-sdk/pull/5155
- [ ] solochain https://github.com/paritytech/polkadot-sdk/pull/5111
- [ ] parachain 

### Use `#[frame::runtime]`
- [ ] minimal 
- [ ] solochain 
- [ ] parachain 

### Use `#[derive_impl]`
Note that this also means in the testing code of the template pallet that lives in each template. For production, there is still an ongoing exploration by @gupnik to see if we can use it or not. See https://github.com/paritytech/polkadot-sdk/pull/5111#discussion_r1687886760

- [ ] minimal 
- [ ] solochain 
- [ ] parachain 

### Provide `GenesisConfig` presets 
The runtime should start exposing at least a `development` genesis-config, that one should 

- [ ] minimal 
- [ ] solochain 
- [ ] parachain https://github.com/paritytech/polkadot-sdk/pull/4739

### Make `node` compilation optional + Provide `chopsticks.yaml`
This is an important step in the direction of omni-nodes: our templates should be such that they encourage you to not build the node all the time. We achieve this by: 

1. Adding configuration + guides on how to locally run your runtime with just chopsticks (and maybe someday with a #5117 or similar)
2. The node doesn't even compile by default when you do `cargo br`. It should be feature gated.

- [ ] minimal 
- [ ] solochain 
- [ ] parachain 

### Mark templates in `substrate-developer-hub` as archived. 
- [ ] https://github.com/substrate-developer-hub/substrate-node-template
- [ ] https://github.com/substrate-developer-hub/substrate-parachain-template

### More ideas? Yes, Sky's the limit! 

There is a lot [more](https://github.com/paritytech/polkadot-sdk/issues/3155#issuecomment-2126934939) that can be done to make the `polkadot-sdk` templates look nice. Be creative and proactive! Look to your favorite tools, repos and templates, and see what elements they have that make enjoy using them, and being them over :)

**Comment by michalkucharczyk** [comment]
Just for a record: here is a comment with some _pending-follow-ups_  improvements that can be done in the context of  _Provide GenesisConfig presets_ task:
https://github.com/paritytech/polkadot-sdk/pull/4739#discussion_r1739021319

**Comment by ndkazu** [comment]
- About **Use #[derive_impl]**:
I might be missing something, but it seems like `#[derive_impl]` is already being used in the minimal template runtime:
→ check_box update needed?

**Comment by Krayt78** [comment]
Doesnt #5991 check the umbrela/Frame for the parachain part?
