### ISSUE TITLE
`pallet_revive` launch tracking issue

### ISSUE THREAD

**Issue by athei** [paritytech/polkadot-sdk#5308]
This issue tracks all the open changes that we need to make to `pallet_revive` so it can YUL contracts. This is only the minimal feature set for the deployment and does not include features that need to be delivered later (JIT). It also only includes changes to the pallet and not other components.

I ordered them by urgency.

```[tasklist]
### Tasks
- [ ] Use `AccountID20` when interfacing with the contract and as internal key for the contract map. This includes implementing the account mapper
- [ ] Fix contract address derivation to be the came as on Eth as tooling might assume those
- [ ] Allow contract instantiation with CREATE1 semantics using account nonce of sender (both for contracts and from an extrinsic) 
- [ ] All generic types (block number, time stamp...) that are loaded into/from contract memory should be u256 **little** endian instead of being configurable.
- [ ] Calling an address without associated code should do a balance transfer
- [ ] Move contract emitted topics from being an actual topic to be just included into the event body
- [ ] Make sure that all `MaxEncodedLen` types which are not fixed size use `read_as_unbounded`. One example where this goes wrong is the `VersionedLocation` of `xcm_send`.
- [ ] Make `block_number` return relay chain block number?
- [ ] Make sure the returned timestamp of `now` makes sense
- [ ] Go through the emitted logs of `pallet_revive` to make sure they make sense
- [ ] Reevaluate our memory calculations in our initialization check and find out if we can increase the maximum stack size
- [ ] Deactivate all syscalls which are not necessary for launch (flagging them unstable)
- [ ] Fix the `sized` and `instruction` benchmarks. Those are bogus right now because they need an PolkaVM assembler to be written properly
```
