### ISSUE TITLE
Tracking issue for QUIC support

### ISSUE THREAD

**Issue by kpp** [paritytech/polkadot-sdk#536]
There are a couple of reasons to support QUIC network protocol.

The first, slightly minor, is that validators are maintaining more than 1000 TCP connections open and are running into file descriptor limits.
Second is we use Yamux for multiplexing multiple substreams into one, which is a rather poor protocol that does the best it can on top of TCP, but can't do more.
Because we can't know the TCP window size from user space, we can't actually properly allocate window sizes to individual substreams. If two or more substreams send a big volume of data, we'll run into head of line blocking issues (This is the same reason why HTTP2 is not so great and is being replaced with HTTP3, if you want to read more)
Third reason is we're suffering from a TCP slow start issue. A TCP connection is almost unused, and suddenly we send for example 2 MiB on it. Because of TCP slow start, it's going to take a rather long time to send these 2 MiBs even if the connection would be capable of sending them quickly.

First attempt was made in https://github.com/paritytech/substrate/pull/6366.

So far there is https://crates.io/crates/libp2p-quic which should be reviewed.

The list of sub issues will be updated time to time:

- [x] TLS 1.3 vs Noise. The golang version uses TLS (see https://github.com/libp2p/specs/blob/master/tls/tls.md#peer-authentication), also there is no nQUIC specs, so to be compatible with libp2p we have to use TLS+QUIC.
- [x] Inspect whether we can replace `x509-signature` with `picky`. The answer is we can replace it with any crate we can including `x509-parser`, `picky`, etc...
- [x] Implement x509 cert serializer, parser, verifier https://github.com/kpp/rust-libp2p/pull/1
- [x] Implement verification of all signature algorithms according to TLS 1.3 standard https://github.com/kpp/rust-libp2p/pull/4
- [x] Implement rustls ServerCertVerifier & ClientCertVerifier https://github.com/kpp/rust-libp2p/pull/6
- [x] Make libp2p-quic binary compatible with the go implementation (a standalone issue) https://github.com/ipfs-rust/libp2p-quic/pull/6
- [x] R&D: a basic QUIC server https://github.com/kpp/rust-libp2p/issues/8
- [x] The existing crate `libp2p-quic` now supports TLS, but there still some issues left.
- [x] Integrate `libp2p-quic` into `rust-libp2p` with the help of its maintainers ~~https://github.com/libp2p/rust-libp2p/pull/2159~~ https://github.com/libp2p/rust-libp2p/pull/2289
- [ ] Integrate `libp2p-quic` into `substrate` https://github.com/paritytech/substrate/pull/11514.

**Comment by burdges** [comment]
I'd assume the benchmarks remain pretty lackluster?

**Comment by Ralith** [comment]
I believe they're thinking of the numbers at https://github.com/paritytech/polkadot-sdk/issues/536#issuecomment-1691857046, which suggest overly pessimistic congestion controller behavior when there's significant latency, which tends to not be reflected by loopback tests. The details I asked for in https://github.com/paritytech/polkadot-sdk/issues/536#issuecomment-1691857065 could help drive further investigation.
