### ISSUE TITLE
Roadmap for allowing browser-embedded nodes to connect to Substrate networks

### ISSUE THREAD

**Issue by tomaka** [paritytech/polkadot-sdk#547]
- [ ] ~~Make it possible for node operators to attach a TLS certificate to their libp2p WebSocket server. I believe this can be done by adding a CLI option that passes a certificate.~~

- [ ] Add a WebRTC "client" in nodes.

- [ ] ~~Implement some mechanism for nodes to relay WebRTC SDPs, in other words to act as signalling servers. This point is quite vague and needs more thoughts.~~

**Comment by tomaka** [comment]
I don't know what the `involved` and `some_time_soon` labels really means, but this really should be done "some time soon". It's a very high priority change for light clients, and just because it's a difficult change shouldn't mean that it should be left on the side to rot.
