### ISSUE TITLE
`fatxpool`: Master issue for upcoming work

### ISSUE THREAD

**Issue by michalkucharczyk** [paritytech/polkadot-sdk#5472]
Following issues are planned for fork-aware transaction pool (follow-up of #4639).
```[tasklist]
### In progress
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5978
- [ ] https://github.com/paritytech/polkadot-sdk/issues/5809
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6008
- [ ] #5490
```

```[tasklist]
### Tasks
- [ ] #5473
- [ ] #5476
- [ ] #5493
- [ ] #5479
- [ ] #5482
- [ ] #5497
- [ ] #5626
- [ ] #5483
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6409
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6831
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6070
- [ ] https://github.com/paritytech/polkadot-sdk/issues/7355
```

```[tasklist]
### Known bugs
- [ ] #5486
- [ ] #5487
- [ ] #5494
```

```[tasklist]
### Improvements
- [ ] #5474
- [ ] https://github.com/paritytech/polkadot-sdk/issues/7071
- [ ] #5491
- [ ] #5495
- [ ] #5492
- [ ] #5489
- [ ] #5496
- [ ] #5485
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6056
- [ ] https://github.com/paritytech/polkadot-sdk/issues/7138
- [ ] https://github.com/paritytech/polkadot-sdk/issues/7399
```

```[tasklist]
### Add missing unit tests
- [ ] #5475
- [ ] #5478
- [ ] #5477
- [ ] #5480
- [ ] #5481
- [ ] #5484
- [ ] #5488
```

And the following improvements are required in transaction test tool:
```[tasklist]
### `ttxt` tasks
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/9
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/10
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/11
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/12
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/13
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/14
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/15
- [ ] https://github.com/michalkucharczyk/tx-test-tool/issues/16
```

**Comment by michalkucharczyk** [comment]
All issues tracked in txpool project:
 https://github.com/orgs/paritytech/projects/156/
