### ISSUE TITLE
Enabling 1k validators & 200 cores on polkadot

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#5867]
The majority of the optimisations we deem necessary for achieving 1k validators and 200 cores polkadot from [this board](https://github.com/orgs/paritytech/projects/119/views/18) had been finished or in the progress to be finished.

This ticket's purpose is to track all the dependencies that need to happen to gradually reach 1k validators on Kusama and Polkadot. That will allow both networks to have a maximum total cores of 200, we don't have any control over the usage of those cores, but hopefully that ramps up as well.

## Checklist to target

Note all the steps are mandatory and are meant to be performed one after the other, if at any step we discovered anything not going according to expectations or if new data is discovered we are meant to pause and reassess the plan.

###  Kusama
- [ ] Increase the number of parachain validators from 500 to 600, monitor load/stability.
- [ ] [approval-voting-parallel](https://github.com/paritytech/polkadot-sdk/issues/5816) is enabled on kusama, monitor load/stability.
- [ ] PVF prioritization PRs https://github.com/paritytech/polkadot-sdk/pull/4837,  is enabled on kusama.
- [ ] [Parachain inherent fixes](https://github.com/paritytech/polkadot-sdk/issues/849) are deployed on kusama.
- [ ] Validators upgrade their specs inline with: https://polkadot.subsquare.io/referenda/1051?tab=timeline.
- [ ] Bump number of [PVF execution workers](https://github.com/paritytech/polkadot-sdk/issues/4126) from 2 to 4
- [ ] Increase the number of parachain validators from 600 to 700, monitor load/stability.
- [ ] Increase the number of parachain validators from 700 to 800, monitor load/stability.
- [ ] Increase the number of parachain validators from 800 to 900, monitor load/stability.
- [ ] Increase the number of parachain validators from 900 to 1000, monitor load/stability.

### Polkadot

All steps have as a pre-requisite that the same step have already been performed on kusama.

- [ ] Increase the number of parachain validators from 400 to 500, monitor load/stability.
- [ ] [approval-voting-parallel](https://github.com/paritytech/polkadot-sdk/issues/5816) is enabled on polkadot, monitor load/stability.
- [ ] PVF prioritization PRs https://github.com/paritytech/polkadot-sdk/pull/4837,  is enabled on polkadot.
- [ ] [Parachain inherent fixes](https://github.com/paritytech/polkadot-sdk/issues/849) are deployed on polkadot.
- [ ] Validators upgrade their specs inline with: https://polkadot.subsquare.io/referenda/1051?tab=timeline.
- [ ] Bump number of [PVF execution workers](https://github.com/paritytech/polkadot-sdk/issues/4126) from 2 to 4
- [ ] Increase the number of parachain validators from 500 to 600, monitor load/stability.
- [ ] Increase the number of parachain validators from 600 to 700, monitor load/stability.
- [ ] Increase the number of parachain validators from 700 to 800, monitor load/stability.
- [ ] Increase the number of parachain validators from 800 to 900, monitor load/stability.
- [ ] Increase the number of parachain validators from 900 to 1000, monitor load/stability.

## Honorable mentions

Migrating from the CPU intensive libp2p to litep2p, https://github.com/paritytech/litep2p/issues/140

**Comment by burdges** [comment]
> we don't have any control over the usage of those cores, but hopefully that ramps up as well.

We should reserve half the cores for gluttons for the near future.  

In theory, we could temporarily cap no-shows for glutton cores, but instead count no-shows, _provided_ we foresee some benefits to pushing faster and collecting data like that.

At some later point, kusama gluttons, without no-show caps, could be transitioned into polkavm contract cores which accepted user transations compiled from solidity, and which we fill using some solidity glutton.  This is purely political, but it provides a nice proof of throughput, before we sell off those cores to people who'll underutilize them.

**Comment by alexggh** [comment]
> We should reserve half the cores for gluttons for the near future.

We already have this one: https://github.com/paritytech/polkadot-sdk/issues/5593, but I don't think should be made as a dependency of increasing the number of validators.

**Comment by alexggh** [comment]
Plan is on-hold indefinitely.
Currently, we have more than enough cores on polkadot, so there is no pressure to increase the number of validators.

**Comment by burdges** [comment]
Aren't we bringing Kusama down to like 700-ish, just to see if we get better results in anything?

**Comment by alexggh** [comment]
> Aren't we bringing Kusama down to like 700-ish, just to see if we get better results in anything?

Kusama currently has just 700 para validators.

**Comment by burdges** [comment]
Ahh oaky, so maybe the issue was reducing the number of validator to the number of para validators.  I've forgotten..
