### ISSUE TITLE
[Deprecation] Treasury Proposals and `spend_local` call

### ISSUE THREAD

**Issue by muharem** [paritytech/polkadot-sdk#5930]
Deprecate the items related to the Gov_v1 treasury spend flow and provide an implementation of the `Pay` trait within the treasury pallet to make it possible to setup the `spend` call to work as `spend_local`.

Deprecated items:
- `Proposals`, `ProposalCount` and `Approvals` storage items;
- `spend_local` and `remove_approval` calls;
- all public items associated exclusively with above items (e.g.  `MaxApprovals`);

Reference issue: https://github.com/paritytech/polkadot-sdk/issues/138

```[tasklist]
### Tasks
- [ ] Hard deprecation by adding a warning message
- [ ] Remove usage of the deprecated feature in the code base
- [ ] Update examples and tutorials
- [ ] Deprecation is noted in the release log
- [ ] Removal version is planned
- [ ] Deprecated feature is removed
- [ ] Removal of the feature is noted in the release log
```

**Comment by davidk-pt** [comment]
I think there's already config of `Paymaster` inside treasury pallet, we need to add another one? Am I missing something?
```
		/// Type for processing spends of [Self::AssetKind] in favor of [`Self::Beneficiary`].
		type Paymaster: Pay<Beneficiary = Self::Beneficiary, AssetKind = Self::AssetKind>;
```
