### ISSUE TITLE
Support for Crate-Specific Features via Umbrella Dependency

### ISSUE THREAD

**Issue by SailorSnoW** [paritytech/polkadot-sdk#5934]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

While managing our dependencies through the Umbrella, we quickly encountered an issue where it seems we are unable to use internal features of the Umbrella's crates. (For instance, `insecure_zero_ed`from pallet-balances, `historical` from pallet-session, etc.)

### Request

Enable the use of specific crate features through the Umbrella.

### Solution

Have any design choices been considered for this case?
For example, we could import these features via the Umbrella by combining the crate name with the feature name, like so:
```toml
pallet-balances-insecure-zero-ed = [
    "pallet-balances?/insecure_zero_ed"
]
```

### Are you willing to help with this request?

Maybe (please elaborate above)

**Comment by ggwpez** [comment]
Maybe as workaround you can try to enable the feature on the crate directly, since rust feature unification should then merge those. Just make sure to use `resolver = 2` in your workspace.

```toml
pallet-balances = { version = "*", features = ["insecure_zero_ed"], default-features = false }
```

Not sure if the `*` will make cargo pick the same version as the umbrella, or if you have to specify it manually...

For more long term solution guess we could do the concatenation with the features? But it can also turn quite ugly. WDYT @kianenigma ?

**Comment by SailorSnoW** [comment]
Well, maybe we could simply do the same as the experimental feature and use only the feature name which will enable all crates having this feature name

https://github.com/paritytech/polkadot-sdk/blob/dada6cea6447ce2730a3f3b43a3b48b7a5c26cf6/umbrella/Cargo.toml#L525-L530

**Comment by ggwpez** [comment]
Depends on what features exactly. I assume that some of them would clash names, but for the big ones it should work.  
What features do you need? `insecure_zero_ed` i guess, what else?  
They can be added here and then in the zepter config:  

https://github.com/paritytech/polkadot-sdk/blob/d73c56de36263b6c446910a4904368d827b753eb/scripts/generate-umbrella.py#L113

**Comment by kianenigma** [comment]
hmm this seems like an issue indeed.

Combining names seems like a time bomb, I would not try this. 

For the ones that we have, we should indeed treat them like `experimental` and just expose them at the top level umbrella. It seems to be the best we can do atm. 

Long term, I hope we can reduce the number of custom feature flag we have. They are not meant to be a gate for "experimental" stuff. So the feature "insecure_zero_ed" would overall go away.

**Comment by SailorSnoW** [comment]
Here is some features that seems important to us to use Umbrella for our runtimes which is currently missing:

- [ ] `historical` from `pallet-session`
- [ ] `metadata-hash` from `substrate-wasm-builder`

**Comment by ggwpez** [comment]
Not sure i get the outcome of this discussion.  
So we do add features like this:

`"pallet-session+historical" = ["pallet-session/historical"]`

To the umbrella crate, yea?

**Comment by kianenigma** [comment]
Is what @bkchr suggested here a good workaround for this? 

https://github.com/paritytech/polkadot-sdk/issues/6987#issuecomment-2609401253

1. pull umbrella and let that dictate your version.
2. Use `some-crate = { version = "*", feature = ["more", "stuff"] }`.

**Comment by huntbounty** [comment]
I may not fully grasp all the implications here. To address this, for each exported crate `crate-a` and each of its features `feat-b`, `feat-c`.. (perhaps excluding `std` etc), there should be a corresponding feature in `polkadot-sdk`, so that it's possible for users to pinpoint the dependency features to enable. Does that sound right to you? 👼 @ggwpez @kianenigma 

If there isn't a naming convention for the feature names in this case yet, we may consider

```toml
[features]
# ...
crate-a-feat-b = ["crate-a?/feature-b"]
crate-a+feat-b = ["crate-a?/feature-b"]
"crate-a+feat-b" = ["crate-a?/feature-b"]
crate-a_feat-b = ["crate-a?/feature-b"]
crate-a_feat-c = ["crate-a?/feature-c"]
# ...
```

* with `-`, easiest to type, but lacking the visual cue separating the crate name and the feature name 
* with `+`, the feature name has to be quoted and what `a+b` means may not be intuitive at first glance (I'd think it enables both `a` and `b` features).

I'd vote for `crate-a-feat-b` (if the visual cue isn't critical) or `crate-a_feat-b`. What do you think? 😊
