### ISSUE TITLE
Follow up for: Use the umbrella crate for the parachain template

### ISSUE THREAD

**Issue by serban300** [paritytech/polkadot-sdk#5993]
Follow up for: https://github.com/paritytech/polkadot-sdk/pull/5991 

Also related to https://github.com/paritytech/polkadot-sdk/issues/4782

Still need to replace the following dependencies with `polkadot-sdk` umbrella dependencies:

- [x] `parachain-template-node` - `sc-tracing`

Getting an error for the `#[polkadot_sdk::sc_tracing::logging::prefix_logs_with("Parachain")]`:
```
error: Could not find `sc-tracing` in `dependencies` or `dev-dependencies` in `/media/serban/data/workplace/sources/polkadot-sdk/templates/parachain/node/Cargo.toml`!
   --> templates/parachain/node/src/service.rs:235:1
    |
235 | #[polkadot_sdk::sc_tracing::logging::prefix_logs_with("Parachain")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `polkadot_sdk::sc_tracing::logging::prefix_logs_with` (in Nightly builds, run with -Z macro-backtrace for more info)
```

- [ ] `parachain-template-runtime` - `cumulus-pallet-parachain-system`

Similar error with the one above when using a macro from `cumulus-pallet-parachain-system`

- [ ] `parachain-template-runtime` - `substrate-wasm-builder` -> the `metadata-hash` feature can't be enabled through the umbrella crate

- [ ] `parachain-template-node` - `prometheus-endpoint` -> not part of the umbrella crate

**Comment by seemantaggarwal** [comment]
I will take this

**Comment by seemantaggarwal** [comment]
So I tried simply removing sc-tracing from polkadot-sdk/templates/parachain/node/Cargo.toml and ran `cargo build --all-features`
and it works, looks like we do not need that anymore atleast

**Comment by seemantaggarwal** [comment]
For referent to @kianenigma and @serban300  https://github.com/paritytech/polkadot-sdk/pull/7464
