### ISSUE TITLE
[testnet bridge] Permissionless dedicated bridge lanes deployment

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#6116]
## Description

The permissionless lanes feature was introduced [here](https://github.com/paritytech/polkadot-sdk/issues/6044), but we want to deploy it on the testnet first.

Since Rococo is shut down, for testnet deployments we will initially use zombienet for end-to-end (e2e) tests, and then proceed with [this issue](https://github.com/paritytech/polkadot-sdk/issues/6112).

## Progress
- [ ] add `drop_threashold` support for congestion
- [ ] use HRMP suspend/resume or revert `report_bridge_status` (but then we need to add source chain router's pallet_instance for congestion - add new extrinsic `report_bridge_congestion_to(origin, bridged_universal_location, Option<pallet_instance>)` extrinsic)
- [ ] for bridge messages pallet on AHs (instead of BHs), implement https://github.com/paritytech/polkadot-sdk/issues/5827
- [ ] add emulated tests: https://github.com/paritytech/polkadot-sdk/issues/5552 (which could be reused for fellows)
- [ ] add zombienet tests https://github.com/paritytech/polkadot-sdk/issues/5709
  - which will be reused for P/K bridge: https://github.com/polkadot-fellows/runtimes/issues/476

## Deployment plan

[Bridges: Permissionless Lanes deployment](https://hackmd.io/3ei1CQhnTBKHBXF3yi2IIg?view).

**Comment by RomarQ** [comment]
Hi @bkontur @acatangiu,

What is the status on this? 

I would like to use BridgeHub to bridge messages between 2 parachains, one in Polkadot and another in Kusama. Is it already possible to use bridge hub for this purpose?

![Image](https://github.com/user-attachments/assets/6024d273-decb-4242-aa04-6cc46a7ccaeb)

**Comment by bkontur** [comment]
@RomarQ Unfortunately, not yet. We are aiming for the end of Q1 2025 to go live on Polkadot/Kusama (after a successful security audit). Our ultimate goal is to deploy this feature on AssetHubs (the upcoming Plaza), so you would just need to replace "Bridge Hub" with "Asset Hub" in your picture.
