### ISSUE TITLE
[Umbrella ticket] Improve unit test coverage for EPM-MB pallet and sub-pallets

### ISSUE THREAD

**Issue by gpestana** [paritytech/polkadot-sdk#6134]
Improve the coverage of unit and integration-tests of the EPM-MB pallet and its sub-pallets.

**Note for mentees**: test cases examples are outlined in https://hackmd.io/ZuzWnVkXSIuO9RZZP444SA

```[tasklist]
### Tasks
- [ ] reasonable test coverage for EPM-MB core pallet
- [ ] reasonable test coverage for signed pallet
- [ ] reasonable test coverage for unsigned pallet
- [ ] reasonable test coverage for verifier pallet
- [ ] integration-tests test coverage
```

**Comment by rockbmb** [comment]
Just to check - it's still ok if I pick this up, correct?

**Comment by kianenigma** [comment]
are either of you working on this?

**Comment by Zebedeusz** [comment]
All the work I did on that was merged in https://github.com/paritytech/polkadot-sdk/pull/6332.
I'm not working on it anymore.

**Comment by rockbmb** [comment]
I'm not, take it away 👍
