### ISSUE TITLE
[Umbrella ticket] Improve `try-state` and `integrity-tests` coverage for EPM-MB pallet and sub-pallets

### ISSUE THREAD

**Issue by gpestana** [paritytech/polkadot-sdk#6135]
Improve the coverage of [try-state](https://paritytech.github.io/polkadot-sdk/master/frame_support/traits/trait.Hooks.html#method.try_state) checks for the EPM-MB and its sub-pallets. In addition, the new EPM-MB and its sub-pallets have a few new config invariants that can and *should* be checked by the [integrity_test](https://paritytech.github.io/polkadot-sdk/master/frame_support/traits/trait.Hooks.html#method.integrity_test) hook.

The EPM-MB pallet and sub-pallets haven't been merged to master yet, check https://github.com/paritytech/polkadot-sdk/pull/6034. 

**Note for mentees**: each of the tasks of this umbrella ticket is a good mentor task for who wants to help with the multi-block election/staking effort. All the storage invariants *should* be documented in the pallet's rustdoc, otherwise ping @gpestana.

```[tasklist]
### Tasks
- [ ] `try-state` / `integrity-test` checks for EPM-MB core
- [ ] `try-state` / `integrity-test` checks for signed pallet
- [ ] `try-state` / `integrity-test` checks for unsigned pallet
- [ ] `try-state` / `integrity-test` checks for verifier pallet
```

**Comment by Krayt78** [comment]
Hi @gpestana along with @ndkazu and @cjumelin we want to tackle this issue :)
