### ISSUE TITLE
META: Weights in AHM

### ISSUE THREAD

**Issue by kianenigma** [paritytech/polkadot-sdk#6151]
Done: 

* Weights in AssetHub, and by extension other system chains are accurate.
* Tools and processes to achieve this documented so that other non-system parachains can also learn. 

 
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/polkadot-sdk/pull/5891
- [ ] https://github.com/paritytech/polkadot-sdk/issues/152
- [ ] https://github.com/paritytech/polkadot-sdk/issues/3581
```
