### ISSUE TITLE
Refactor pallets to V2 bench syntax

### ISSUE THREAD

**Issue by ggwpez** [paritytech/polkadot-sdk#6202]
We should move all remaining pallets to the V2 benchmarking syntax. It seems to be stable and feature complete.

👉 If you want to work on this: Please check that there is not already a merge request for the pallet that you want to work on. Please pick only one or a small set of pallets - not all at once. This keeps review times low.

Full pallet list:

- [x] pallet-babe #6311 
- [x] pallet-child-bounties #6310 
- [x] pallet-democracy https://github.com/paritytech/polkadot-sdk/pull/6509
- [x] pallet-election-provider-multi-phase #6316 
- [x] pallet-election-provider-support #6315 
- [x] pallet-elections-phragmen #6314 
- [x] pallet-fast-unstake #6311 
- [x] pallet-glutton #6296
- [x] pallet-grandpa https://github.com/paritytech/polkadot-sdk/pull/6073
- [x] pallet-im-online #6295
- [x] pallet-indices #6290 
- [x] pallet-multisig #5995 
- [x] pallet-nft-fractionalization #6301
- [x] pallet-nis #6293
- [x] pallet-nomination-pools-benchmarking #6302
- [x] pallet-offences #6300 
- [x] pallet-preimage #6277 
- [x] pallet-proxy #5995
- [x] pallet-recovery #6299
- [x] pallet-remark #6291
- [x] pallet-scheduler #6292
- [x] pallet-session #6294
- [x] pallet-society #6367
- [x] pallet-state-trie-migration #6617 
- [x] pallet-timestamp #6258 
- [x] pallet-transaction-storage #6290 
- [x] pallet-utility https://github.com/paritytech/polkadot-sdk/pull/6276
- [x] pallet-vesting #6254 

Then the Polkadot and Cumulus pallets:

- [x] ./cumulus/pallets/session-benchmarking/src/inner.rs #6564 
- [x] ./polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs #6618 
- [x] ./polkadot/xcm/pallet-xcm/src/benchmarking.rs #6501
- [x] ./polkadot/runtime/common/src/claims.rs #6318
- [x] ./polkadot/runtime/common/src/crowdloan/mod.rs #6615 
- [x] ./polkadot/runtime/common/src/paras_registrar/mod.rs #6616 
- [x] ./polkadot/runtime/common/src/auctions.rs #6613
- [x] ./polkadot/runtime/common/src/slots/mod.rs #6614 
- [x] ./polkadot/runtime/parachains/src/initializer/benchmarking.rs #6612
- [x] ./polkadot/runtime/parachains/src/configuration/benchmarking.rs #6607
- [x] ./polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs #6606 
- [x] ./polkadot/runtime/parachains/src/inclusion/benchmarking.rs #6368 
- [x] ./polkadot/runtime/parachains/src/disputes/benchmarking.rs #6577 
- [x] ./polkadot/runtime/parachains/src/disputes/slashing/benchmarking.rs #6577 
- [x] ./polkadot/runtime/parachains/src/paras/benchmarking.rs #6576

**Comment by AurevoirXavier** [comment]
- multisig https://github.com/paritytech/polkadot-sdk/pull/5995
- proxy https://github.com/paritytech/polkadot-sdk/pull/6211

**Comment by programskillforverification** [comment]
Pick up:
- transaction-storage, indices

**Comment by clangenb** [comment]
Pickup:

* pallet-remark, pallet-scheduler

**Comment by AurevoirXavier** [comment]
> Pickup:
> 
> * pallet-remark, pallet-scheduler

Hi, I'm working scheduler currently. :)

**Comment by clangenb** [comment]
Thanks for the quick response 🚀

**Comment by clangenb** [comment]
Pickup:
* pallet-sessions
* pallet-recovery
* pallet-offences

**Comment by AurevoirXavier** [comment]
> Pick up:
> 
> * transaction-storage, indices
> * babe, child-bounties, democracy
> * fast-unstake, glutton

Well... I recommend handling them individually and providing updates here, rather than claiming them all at once.

**Comment by programskillforverification** [comment]
> > Pick up:
> > 
> > * transaction-storage, indices
> > * babe, child-bounties, democracy
> > * fast-unstake, glutton
> 
> Well... I recommend handling them individually and providing updates here, rather than claiming them all at once.

If so, we have to create many pr, that's a little tedious, and this page will extend too long

**Comment by AurevoirXavier** [comment]
> If so, we have to create many pr, that's a little tedious, and this page will extend too long

That's why there is a summary on the top.

And this makes easier to collaborate with others.

But the most important reason is:

```
One PR for one task = Easy review
```

**Comment by clangenb** [comment]
Pickup:
* pallet-nomination-pools
* pallet-nft-fractionalization

**Comment by re-gius** [comment]
Working on pallet-claims in https://github.com/paritytech/polkadot-sdk/pull/6318

**Comment by re-gius** [comment]
Working on pallet-society in #6367

**Comment by clangenb** [comment]
Pickup:

* pallet-fast-unstake
* pallet-election-phragmen

**Comment by clangenb** [comment]
Pickup:

* ./polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs

**Comment by kianenigma** [comment]
Great work being done around all PRs made here. Thank you to all contributors, and thank you @re-gius for coordinating. 

1. All of these PRs can be merged with `Silent` tag as they are backwards compat. 
2. @re-gius please reward those who work on this and provide a DOT address with a `/tip small`.

**Comment by re-gius** [comment]
> 2. @re-gius please reward those who work on this and provide a DOT address with a `/tip small`.

I'm checking all the merged PRs and rewarding with `/tip small` one in two for each user (as @shawntabrizi started doing).

**Comment by ndkazu** [comment]
Hello,
I am working on **pallet-democracy** migration to  benchmarks V2 in the following PR:
https://github.com/paritytech/polkadot-sdk/pull/6509

**Comment by Krayt78** [comment]
Hi ! 
Since i am stuck on some bizarre error on the previous PR, here is in the meantime the migration for cumulus-pallet-session-benchmarking which is available at this PR #6564.

Do i need any other test on my end than "cargo test -p name_of_pallet --features runtime-benchmarks" to make sure that its ok before sending to review ?

**Comment by Krayt78** [comment]
> > Hi ! I started working on pallet-offences-benchmark migration to V2 in this draft PR #6543
> 
> There is already a PR for pallet offences since a while from me. Unfortunately, they haven't updated the main issue message, but you can see it in my comment. :)

Oops my bad didnt see your comment, i will delete my PR then

**Comment by clangenb** [comment]
Pickup:
* ./polkadot/runtime/parachains/src/paras/benchmarking.rs
* ./polkadot/runtime/parachains/src/disputes/benchmarking.rs
* ./polkadot/runtime/parachains/src/disputes/slashing/benchmarking.rs

**Comment by Krayt78** [comment]
I am picking up  ./polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs

**Comment by Krayt78** [comment]
- [x] pallet-babe https://github.com/paritytech/polkadot-sdk/pull/6311
- [x]  pallet-child-bounties https://github.com/paritytech/polkadot-sdk/pull/6310
- [x]  pallet-democracy https://github.com/paritytech/polkadot-sdk/pull/6509
- [x]  pallet-election-provider-multi-phase https://github.com/paritytech/polkadot-sdk/pull/6316
- [x]  pallet-election-provider-support https://github.com/paritytech/polkadot-sdk/pull/6315
- [x]  pallet-elections-phragmen https://github.com/paritytech/polkadot-sdk/pull/6314
- [x]  pallet-fast-unstake https://github.com/paritytech/polkadot-sdk/pull/6311
- [x]  pallet-glutton https://github.com/paritytech/polkadot-sdk/pull/6296
- [x]  pallet-grandpa https://github.com/paritytech/polkadot-sdk/pull/6073
- [x]  pallet-im-online https://github.com/paritytech/polkadot-sdk/pull/6295
- [x]  pallet-indices https://github.com/paritytech/polkadot-sdk/pull/6290
- [x]  pallet-multisig https://github.com/paritytech/polkadot-sdk/pull/5995
- [x]  pallet-nft-fractionalization https://github.com/paritytech/polkadot-sdk/pull/6301
- [x]  pallet-nis https://github.com/paritytech/polkadot-sdk/pull/6293
- [ ]  pallet-nomination-pools
- [x]  pallet-nomination-pools-benchmarking https://github.com/paritytech/polkadot-sdk/pull/6302
- [ ]  pallet-offences
- [x]  pallet-preimage https://github.com/paritytech/polkadot-sdk/pull/6277
- [x]  pallet-proxy https://github.com/paritytech/polkadot-sdk/pull/5995
- [x]  pallet-recovery https://github.com/paritytech/polkadot-sdk/pull/6299
- [x]  pallet-remark https://github.com/paritytech/polkadot-sdk/pull/6291
- [x]  pallet-scheduler https://github.com/paritytech/polkadot-sdk/pull/6292
- [x]  pallet-session https://github.com/paritytech/polkadot-sdk/pull/6294
- [x]  pallet-society https://github.com/paritytech/polkadot-sdk/pull/6367
- [ ]  pallet-state-trie-migration
- [x]  pallet-timestamp https://github.com/paritytech/polkadot-sdk/pull/6258
- [x]  pallet-transaction-storage https://github.com/paritytech/polkadot-sdk/pull/6290
- [x]  pallet-utility https://github.com/paritytech/polkadot-sdk/pull/6276
- [x]  pallet-vesting https://github.com/paritytech/polkadot-sdk/pull/6254
- [ ] Then the Polkadot and Cumulus pallets:
- [ ] 
- [x]  ./cumulus/pallets/session-benchmarking/src/inner.rs
- [ ]  ./polkadot/xcm/pallet-xcm-benchmarks/src/generic/benchmarking.rs
- [ ]  ./polkadot/xcm/pallet-xcm/src/benchmarking.rs
- [x]  ./polkadot/runtime/common/src/claims.rs https://github.com/paritytech/polkadot-sdk/pull/6318
- [x]  ./polkadot/runtime/common/src/crowdloan/mod.rs
- [x]  ./polkadot/runtime/common/src/paras_registrar/mod.rs
- [x]  ./polkadot/runtime/common/src/auctions.rs
- [x]  ./polkadot/runtime/common/src/slots/mod.rs
- [x]  ./polkadot/runtime/parachains/src/initializer/benchmarking.rs
- [x]  ./polkadot/runtime/parachains/src/configuration/benchmarking.rs
- [x]  ./polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs
- [ ]  ./polkadot/runtime/parachains/src/inclusion/benchmarking.rs
- [ ]  ./polkadot/runtime/parachains/src/disputes/benchmarking.rs
- [ ]  ./polkadot/runtime/parachains/src/disputes/slashing/benchmarking.rs
- [ ]  ./polkadot/runtime/parachains/src/paras/benchmarking.rs

**Comment by Krayt78** [comment]
Besides the pallet-nomination-pools that idk if its a duplicate of pallet-nomination-pools-benchmarking, all the other tasks are ready to be reviewed :)

**Comment by re-gius** [comment]
> I am not really happy how the PRs to this issue are tackled. I deliberately made my PRs almost atomic in order to have quick review times. They are dangling forever after all, until they vanish in the hidden comments section, so another dev creates a PR for the same subtask, which is then reviewed within a few days and merged - not exactly motivating. I know it is the dev's responsibility to check for duplicates, but it is hard in this setup.
> 
> I see the difficulties in managing the PRs and that the reviewers have many other tasks to do so a timely review is not always possible, so what can we do?


If your PR has not been reviewed by anyone after a week being ready to be reviewed, you can ping me in a comment from the PR.

**Comment by clangenb** [comment]
Ok, thanks a lot for the constructive hint, I shall do that! 👍

**Comment by re-gius** [comment]
> Edit: What about those that you already reviewed, but the second reviewer is missing?

Let's give it a couple of weeks, then I'll check everything and see what's the status

**Comment by re-gius** [comment]
The message on top has been updated, please check if there's something missing/wrong. Those will be the PRs to review (+ tip)

**Comment by re-gius** [comment]
Thanks to everyone who helped with the issue. Every pallet has been now migrated to v2 benchmarking.
