### ISSUE TITLE
Umbrella ticket for multi-block election tasks to improve after PR#6034

### ISSUE THREAD

**Issue by gpestana** [paritytech/polkadot-sdk#6498]
These tasks are part of the feedback from the https://github.com/paritytech/polkadot-sdk/pull/6034 review, they should be closed *before* multi-block is used in Polkadot and Kusama.

- [x] https://github.com/paritytech/polkadot-sdk/issues/6237 
  - implemented in https://github.com/paritytech/polkadot-sdk/pull/6482, under review
- [ ] [WIP] https://github.com/paritytech/polkadot-sdk/issues/6328 
  - option 1 wip in https://github.com/paritytech/polkadot-sdk/pull/6510
  - option 2 wip in https://github.com/paritytech/polkadot-sdk/pull/6520
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6499
- [ ] https://github.com/paritytech/polkadot-sdk/issues/6136
