### ISSUE TITLE
Define extrinsic for ordering, again based on optimal controller (fixed price, getting burned/going to treasury + tip for block producer)

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#725]
Assuming that once submitted to the runtime a bid will relatively soon result in a claimed core, we can re-use the mortality of extrinsics. The mortality will only be relevant in the transaction pool, once accepted by the runtime and queued, it becomes "immortal" and will result in an assigned core "soon". 

This lifetime handling poses the requirement on the queue to never grow too large, otherwise more elaborate lifetime requirements might arise.

The extrinsic should include:

1. A maximum price: if spot price is higher, the order will be rejected by the extrinsic - weight based fees still to be paid.
2. An optional tip for the block producer.

Once submitted to the runtime and queued, the signing account will be charged the current block's spot price the normal fee and the given tip. Hence with the given mortality the user can have some idea on realistic spot price fluctuations.

There are certain kinds of "invalid" order extrinsics that will only be caught by the extrinisic call itself and not the transaction pool. We will just drop those extrinsics, there is no harm done as a fee has already been paid. From a user perspective this is still bad though and we should make room for error small.

# Todos

- [ ] Additional validation (within the extrinsic, user gets charged even if failing):
   - [ ] Specified ParaId exists/has a registered PVF - (that has been pre-checked already?)
   - [ ] ParaId is not a parachain already (we don't yet support parachain boost)
   - [ ] The bidder is actually related to that ParaId - might be good to be able to check as well. (could be left out in a first impl)
- [ ] Actually place the order
