### ISSUE TITLE
Get a parathread to author a block on Versi

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#727]
# Goals

- Get everything going so we have a parathread successfully author a block on Versi.
- Everything has to be secure
- Good enough to be merged to master (but disabled for production networks)
- Have something working to iterate on

# Non goals

1. does not need to be pretty
2. Bid integration into cumulus (the bid will be sent manually via e.g. polkadotjs)

# Steps

## Getting bids in

- [x] paritytech/polkadot-sdk#726
- [x] paritytech/polkadot#6644
- [x] paritytech/polkadot-sdk#724
- [x] paritytech/polkadot#6646
- [x] paritytech/polkadot-sdk#723

## Scheduler

- [x] Implement assignment provider that dispatches to parathreads and parachains.
- [x] Implement claim queue with a configurable size, to be filled from [assignment providers](https://github.com/paritytech/polkadot/pull/6625/files#diff-ce4dcc5386ca8581c6c6cf22e6b03e37b6ed0584cb4256560b4dfc53fc3e6d8dR181).
- [x] Provide [`availability_cores`](https://github.com/paritytech/polkadot/blob/b5157a38792e5b65ae14501a348c9886468829d3/primitives/src/runtime_api.rs#L134) call based on the claim queue.

## Collator

- [x] Setup some simple parathread, doing something interesting/funny: We can re-use some exiting example parachain
- [x] Setup collator waiting for its paraid to be scheduled to author a block

## Put it together
- [ ] Fix any bugs found on Zombienet
- [ ] Deploy on Versi
- [ ] Register parathread
- [ ] Order a core

# Follow ups (not part of this ticket):

- Make it pretty
- Cumulus integration:
  - secure account abstraction useful for automated bidding on collator (see [here](https://github.com/paritytech/polkadot/pull/6625/files#diff-ce4dcc5386ca8581c6c6cf22e6b03e37b6ed0584cb4256560b4dfc53fc3e6d8dR257))
  - integrate automated bidding functionality in Cumulus (e.g. based on how full the transaction pool is/bid once per day/hour/...)
    - Configuration: Max price to pay, tip to pay, min needed transactions in transaction pool ...
  - coordinate announcements/ involve community - maybe get some alpha/beta testers, ...
  - launch on Kusama
  - launch on Polkadot
