### ISSUE TITLE
Disputes Slashing/Hardening

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot-sdk#750]
# The Vision

Polkadot is a sharded blockchain. Some validators check some of the parachain blocks. When there's a disagreement about validity of parachain block, a dispute process starts. The checks will escalate to every validator. Once the dispute is resolved, we need to slash and disable validators accordingly to their misbehavior.

Board [here](https://github.com/orgs/paritytech/projects/64/views/1).

# Disputes

General goal of disputes improvements is to make them more spam resilient.

# Slashing
## Overall Strategy

Designing slashing systems is a very complex topic and pretty much impossible to get 100% right, especially if you consider real world issues, like machines not being equal, bugs, load variance, hardware faults, ... Therefore we need to be able to rely on governance for fixing any faulty slashes. By being able to rely on governance in extreme edge cases we can err on making the system more secure.

For this we need to ensure/overall strategy:

- [x] Unjustified slashes won't have a significant impact on validators, if reverted by governance. In particular validators should not [lose their nominators](https://github.com/paritytech/substrate/pull/12420). 
- [ ] Disabling of honest validators (due to unjustified slashes), will never be threatening the system's security. (Security over liveness.)
- [ ] Make handling of time more deterministic/robust (outside of scope for this ticket, will be a separate project: time disputes)
- [ ] Add all of this to the guide (describe the overall strategy for handling slashing)

## Plan Details

- [x] Current-session disputes slashing https://github.com/paritytech/polkadot/pull/5535.
- [ ] ~~Test the limits of the slashing logic in substrate https://github.com/paritytech/polkadot/pull/5978~~ (no longer necessary now that chilling has been removed)
- [ ] Ensure there are no disputes due to bugs on Kusama https://github.com/paritytech/polkadot/issues/5952
- [x] Enable slashing on Kusama paritytech/polkadot#5974 
- [x] Enable slashing on Polkadot https://github.com/paritytech/polkadot/pull/6960
- [ ] Past-session disputes slashing paritytech/polkadot#5947 
- [ ] Validator disabling paritytech/polkadot#5948 
- [ ] Escalate punishment on repeated disputes https://github.com/paritytech/polkadot/issues/5946
- [ ] Enable past-session slashing and disabling on Kusama
- [ ] Enable past-session slashing and disabling on Polkadot
