### ISSUE TITLE
disputes: implement validator disabling (Stale)

### ISSUE THREAD

**Issue by ordian** [paritytech/polkadot-sdk#784]
⚠️ **FOR THE MOST UP TO DATE INFO REFER TO:** [Disabling Project Board](https://github.com/orgs/paritytech/projects/119/views/15) and this meta overview [State of Disabling](https://github.com/paritytech/polkadot-sdk/issues/4359) ⚠️

---

Once a dispute is concluded and an offence is submitted with `DisableStrategy::Always`, a validator will be added to `DisabledValidators` list.

Implement on-chain and off-chain logic to ignore dispute votes for X sessions. Optionally, we can ignore backing and approval votes and remove from the reserved validator set on the network level.

- [x] [Gather requirements](https://github.com/paritytech/polkadot-sdk/issues/784) across stack
- [x] Design unified disabling strategy (https://github.com/paritytech/polkadot-sdk/issues/1961)
- [x] Track disabled validators #2950
- [x] Read disabled status from the runtime and apply on node side, for ignoring votes for example in dispute-coordinator.
  * [x] https://github.com/paritytech/polkadot-sdk/issues/1591 https://github.com/paritytech/polkadot-sdk/pull/1841
  * [x] https://github.com/paritytech/polkadot-sdk/issues/1592 https://github.com/paritytech/polkadot-sdk/pull/1863
  * [x] dispute-coordinator - #2225 
- [x] Make disabled state persisted for full era (to avoid repeated slashes)
- [x] Remove I am online slash
- [x] No chilling: Validators should get re-elected as long as they have enough stake
- [x] Handle validators of previous era correctly in [disputes](https://github.com/paritytech/polkadot-sdk/issues/784#issuecomment-1765014451)
- [x] Implement [re-enabling](https://github.com/paritytech/polkadot-sdk/issues/2418)
- [x] Testing
  * [x] https://github.com/paritytech/polkadot-sdk/issues/1590
  * [x] https://github.com/paritytech/polkadot-sdk/issues/2249
- [ ] Provide tooling and instruct validators to monitor for slash events, so we can expect honest operators to react quickly to issues. (Within an era.)
- [ ] Cleanup tasks
  * [ ] https://github.com/paritytech/polkadot-sdk/issues/1940

Possibly related paper [here](https://www.usenix.org/legacy/events/nsdi09/tech/full_papers/clement/clement.pdf).

⚠️ **FOR THE MOST UP TO DATE INFO REFER TO:** [Disabling Project Board](https://github.com/orgs/paritytech/projects/119/views/15)  ⚠️

## Goals for new validator disabling/Definition of Done

1. Not affecting consensus - disabling can never become a security threat.
2. Handling broken validators nicely (prevent continuous spam).
3. Plays well with existing disabling in substrate
4. Makes sure to never break.
5. (Consequence of the above): We can enable slashing - safe and securely.

## Timeline

As quickly as possible, definitely by the end of the year.

**Comment by Overkillus** [comment]
Going back to some of the original requirements:
 
 > 1. For https://github.com/paritytech/polkadot-sdk/issues/635, we need disablement being proportional to the slash.

I don't believe proportional disabling is needed at all as explained in [here](https://github.com/paritytech/polkadot-sdk/issues/635#issuecomment-1705399466).

> 2 is conflicting with 1, as a small slash would result in barely any rate limiting. 

If 1 doesn't require proportional disabling then there is no longer any conflict between them and we can simply disable fully even for minor slashes in spirit of...

> if a node is misbehaving it is definitely better to have it disabled and protect the network this way, than keep slashing the node over and over again for the same flaw.

Which is essentially aiming to protect honest nodes with minimal slashing by fully disabling it. 

We recently had a chat about it but I'd point it out here on record. Disabling on minor slashes and accumulating slashes should both provide enough security as a deterrent against repeating offences, but disabling for minor offences is more lenient for honest faulty nodes and that's why we prefer it. Ideally we'd have both disabling AND accumulating as attackers can still commit multiple minor offences  (for instance invalid on valid disputes) in the same block before they get punished and disabled, but damages done should be minimal so it's not a huge priority.

**Comment by burdges** [comment]
We've parallel discussion in https://github.com/paritytech/polkadot-sdk/issues/635#issuecomment-1705789752 btw

**Comment by Overkillus** [comment]
Potential disabling strategy direction partially based on a call with @eskimor:

Write-up is based on the idea that:
Disabling is (generally) not a security* requirement but a liveness** optimisation.

*Security = Invalid candidates cannot go through (or are statistically very improbable)
**Liveness = Valid candidates can go through (at a decent pace)

**TLDR** at the bottom!


# Nature of Disabling

By disabling we mean directly setting some active validators as disabled which would prohibit them from participating in all or some parts of the consensus.

A simple argument for disabling is that if someone is already slashed 100% and they have nothing to loose they could cause harm to the network and should be silenced.

It is worth noticing that even if we don't have ANY direct disabling in the system slashed nodes will get eventually forced out of the active validator set due to insufficient funds in the next validator election. This will for all intents and purposes force them out (akin to disabling), simply with a higher latency (24-48h). 

There are a few difference between disabling directly and getting forced out at the end of an era:
- latency (next few blocks for direct and 24-48h for getting pushed out organically)
- effects on the size of the current active validator pool (direct can lower the size if we fully disable)
- granularity (direct disabling could remove only a portion of validator privileges instead of all)

# What happens with no direct disabling?

If there is no disabling a new type of an attacker has to be considered - a validator that is already slashed 100% and has nothing to lose. What damage can he cause during his window of activity?

1. Liveness attacks:
1.1 Break sharding (with mass no-shows or mass disputes): It forces everyone to do all the work which affects liveness but doesn't kill it completely. The chain can progress at a slow rate.
1.2 Mass invalid candidate backing: Spawns a lot of worthless work that needs to be done but it is bounded by backing numbers. Honest backers will still back valid candidates and that cannot be stopped. Honest block authors will eventually select valid candidates and even if disputed they will win and progress the chain.

2. Security attacks:
2.1 The best and possibly only way to affect security is by getting lucky in the approval process. Currently ~30 approvals are needed to pass approval voting and if by chance all of them would be malicious they could get a single candidate through. Chance for that is around `4*10^-15`. The concern is that by not disabling attackers they could get significantly more tries. Assuming they can back invalid candidates on 50 cores for 48 hours straight and only those candidates get included it still gives a `7*10^-9` chance of success which is abysmal considering the cost (all malicious stake slashed). Their chances can get higher if we consider randomness manipulation in 1/3 of cases where they are block authors. This COULD be a problem and it would necessitate further calculations (but that should't be necessary based on later sections). 

Attack 1.2 and 2.1 should generally be pretty futile as a solo attacker while 1.1 could be possible with mass disputes even from a single attacker. 

Eventually those attackers (after 1-2 eras, 24-48h) will get pushed out during the election. The cost was paid and someone was punished simply with a relatively high latency.

# Risk of disabling

The primary risk behind having _any_ sort of disabling is that it is a double-edged sword that in case of any dispute bugs could disable honest nodes or be abused by attackers to specifically attack honest nodes. Disabling honest nodes could tip the scales between honest and dishonest nodes and destabilise the protocol. Honest nodes being pushed out of consensus is primarily a problem for approval voting and disputes where a supermajority is required.

It is worth noting that is is fundamentally a defence in depth strategy because if we assume disputes are perfect it should not be a real concern. In reality disputes are difficult to get right, and non-determinism and happen so defence in depth is crucial when handling those subsystems.

What about slashes with no direct disabling?

Slashing by itself is less of a problem due to its high latency of getting pushed out of the validator set. It still affects the honest slashed node in the short term (lost funds), if the slash was truly unjustified the governance should refund the tokens after an investigation. So generally in the long term no harm will be done. It gives 24-48 hours to react in those cases which is at least a small buffer further escalate if an attack pushing out honest nodes out of consensus would show up. 

If we compare it with direct disabling that can strike incredibly quickly (as quickly as few disputes can conclude), it is possible to push out a significant portion of honest validators.

# Mitigation

Firstly, how can we mitigate the risk of disabling?

## Mitigating risks of disabling

We have a few options available in our arsenal. 
- not implement direct disabling (very naive base case)
- heavily bound direct disabling (probably well below 1/3 to not even get close to the risky threshold)
- limit the scope of disabling so it's not as risky (but hopefully still has some of its benefits)

Bounding disabling will be needed nevertheless and it's just a matter of what value to choose for it. The mot obvious and bold one is simply 1/3.

When it comes to limiting the scope of disabling to address the risks this part of the analysis gives us a direct hint:

> Honest nodes being pushed out of consensus is primarily a problem for approval voting and disputes where a supermajority is required.

Based on the above we can make it so:
- Approval voting is allowed during disablement.
If this is the case we eliminate any risks of pushing out honest nodes and increasing the odds of malicious ones. The benefits of disabling here would also be minimal and they would affect liveness only.
- Dispute voting is allowed during disablement.
To not alienate potentially disabled honest nodes we also need to allow them to participate.

## Mitigating the fundamental risks 

Those are the risks that show up when there is no disabling at all so:

1. Liveness attacks:
1.1 Break sharding (with mass no-shows or mass disputes)
1.2 Mass invalid candidate backing
2. Security attacks:
2.1 Getting lucky in approval voting

To address the above we can further alter the disabled status:
- 1.1: Dispute voting is allowed **but limited** during disablement.
To be precise honest nodes do not respond to disabled dispute statements (but they do record them). If honest nodes encounter a single honest non-disabled dispute participant they can escalate the dispute into an effective state. This still removes the risk of alienating honest disabled nodes as previously established while preventing easy mass dispute spam attack. Mass no-show is still possible but it is the least concerning of all the attacks (temporary, high numbers needed, opportunity cost, no direct benefit).
- 1.2 & 2.1: Backing is not allowed during disablement.
This drastically reduces the amount of attempts they have during their window of activity. Even if some honest nodes get disabled this is not an issue as the network will still maintain liveness (even if slightly diminished) with a 1/2 or even 1/3 of validators.

# Disabling strategy:

- Disable up to 1/3 of the set.
- If limit reached simply no longer disable.
- Disable even for minor slashes.
- No proportional disabling is needed (based on reasoning in [here](https://github.com/paritytech/polkadot-sdk/issues/635#issuecomment-1705399466) combined with no disabling in approvals)

## Definition of validator disablement:

- Backing is not allowed
- Approval voting is allowed
- Dispute voting is allowed but limited (not escalated when coming from disabled nodes)

# Summary

This disablement strategy allows for maximising the liveness benefits from direct disabling without any extra security concerns. parachains should always stay live enough to be able to make at least some progress and no forcing out of honest nodes is possible (at least in the short term - era).

Practically it makes it so that even if there is some PVF nondeterminism that can be exploited we have at least 24-48 hours until it starts forcing nodes out of consensus (approvals and disputes in that case) while maintaining the benefits of early mitigation through limited direct disabling.

# Open questions

Should block production be blocked for disabled validators?

Are there any other side-effects of disablement in Substrate?

Can governance react fast enough in cases where honest validators are getting slashed and will be pushed out during the next election?

# TLDR

Even if we don't have disabling slashed validators get forced out at the end of an era (akin to getting disabled).

Direct disabling within the same era (low latency disabling) can aim to improve liveness and not touch security.

NPoS elections and getting forced out due to insufficient funds (high latency disabling) protects security in the long run but kicking out bad actors, but giving governance more time to react in edge cases.

Direct disabling (what happens directly after getting slashed):
- fully blocks backing
- partially blocks disputes
- does not block approval voting

Disable up to 1/3 of the network.

Thanks to above direct disabling can never affect security by disabling too many validators as a defence in depth measure.

**Comment by ordian** [comment]
> Should block production be blocked for disabled validators?

Yes, this is already the case in Substrate. Since we don't have any punishment for producing an invalid block, we should not allow another waster of resources.

https://github.com/paritytech/polkadot-sdk/blob/c0a4ce1fc87b7b39bc307072e60db97ade3cd6be/substrate/frame/babe/src/lib.rs#L360-L365

> 1.1: Dispute voting is allowed but limited during disablement.
> To be precise honest nodes do not respond to disabled dispute statements

Should we also reject dispute imports in the runtime where the only against votes are from the disabled validators? I guess this is less of an issue, since we need at least f+1 votes for the import to succeed, otherwise it's rejected in the runtime. And since we don't cast our vote, f+1 votes would be difficult to get (unless enough nodes are running an old validator version).

Overall this seems like a solid plan 👍 

We should look into all other types of offences (e.g. beefy equivocations) and make sure this works well for them or if there are any other adjustments needed. 

> Can governance react fast enough in cases where honest validators are getting slashed and will be pushed out during the next election?

Slashing can be reverted easily, since it's not applied instantly, but I highly doubt that Governance can react quickly enough before the next session, especially on Kusama, so we should not rely on that.

**Comment by eskimor** [comment]
> Slashing can be reverted easily, since it's not applied instantly, but I highly doubt that Governance can react quickly enough before the next session, especially on Kusama, so we should not rely on that.

Can we fix that? Note that Governance does not need to react within a session (except if we are forcing a new election, which we probably should not do then!), but only within an era. If we mitigated the risk of honest nodes(and stash) getting kicked out at the next election, we would be golden when it comes to security issues caused by non-determinism.

**Comment by Overkillus** [comment]
One point that I'll repeat from the above write-up is:

> It is worth noting that is is fundamentally a defence in depth strategy because if we assume disputes are perfect it should not be a real concern. 

What I mean by that that if slashing honest nodes is not possible we have no real problems or concerns. The strategy above is simply aiming to mitigate the damage IF something goes wrong. And if it goes wrong it means that our assumptions are broken (either nondeterminism or protocol loopholes slipped through) and it will be extremely hard to cover every base perfectly. Because it is a defence in depth strat we don't need it to perfectly cover everything but at least serve as a damage control reducing or delaying the aftermath.

> Should we also reject dispute imports in the runtime where the only against votes are from the disabled validators? I guess this is less of an issue, since we need at least f+1 votes for the import to succeed, otherwise it's rejected in the runtime. And since we don't cast our vote, f+1 votes would be difficult to get (unless enough nodes are running an old validator version).

Shouldn't be an issue so I'd keep it as it is. Crossing 1/3 will not be easy as you pointed out.

> Slashing can be reverted easily, since it's not applied instantly, but I highly doubt that Governance can react quickly enough before the next session, especially on Kusama, so we should not rely on that.

I don't think we should design the Polkadot protocol under the assumption that it has to work with Kusama parametrisation. End goal is the best possible state of things on Polkadot and Kusama is there to simply test what can be tested. Kusama is more agile to promote quick testing and not to block us from deploying optimal parameters on Polkadot. My 2 cents at least.

> but I highly doubt that Governance can react quickly enough before the next session, 

Session? Do you mean era? Elections happen once per era AFAIK so that's 24h and NPoS elections are quite heavy to compute so they are computed some time in advance as well. If you are slashed at the end of an era I am genuinely not sure how it plays out with elections since it might invalidate some precomputed solutions. (Could that be an attack vector? By invalidating some solutions you could use your foreknowledge to make it so your solution wins the election... Need to investigate that more.)

In general I was assuming a 24-48h window for getting organically kicked out after an election. So 1 era buffer. It is a defence in depth measure so having this time is better than having none (with instant direct disabling) and it only becomes relevant if there's a protocol mistake or nondeterminism we didn't anticipate. 

In general disputes should not happen. If a dispute happened everyone should be on high alert and fellowship / people invested in governance should immediately investigate. If you as a node operator believe you were unfairly slashed you should swiftly raise an alarm bell. So the 24-48h seem like enough to at least realise something is going on.

**Comment by eskimor** [comment]
> So the 24-48h seem like enough to at least realise something is going on.|

It is most likely enough time to react, but possibly not enough time to have some action enacted on chain. Confirmation periods and stuff are quite long on Polkadot also as Andronik pointed out, this could happen close to the end of an era + we might have things like a forced new era....

Therefore I think relying on Governance to be able to react fast enough is a non starter unfortunately. Not doing accumulative slashes + minimizing the occasions of 100% slashes as much as possible should get us pretty far.

So far mostly backers can be slashed 100%, but they can also way more easily be protected than approval voters, because we can have stricter limits on everything here. 

With this I can already sleep quite well, we just need to make sure that the reasoning is documented in the [guide and code](https://github.com/paritytech/polkadot-sdk/issues/635), so we maintain this property over time.

**Comment by ordian** [comment]
> I started looking into it and compiling a list of offences. Didn't finish it yet but agree that having that would be very helpful. I'd appreciate some pointers into where to look into all of them. For instance BEEFY didn't even cross my mind.

https://github.com/search?q=repo%3Aparitytech%2Fpolkadot-sdk%20report_offence&type=code
So far we are using offences pallet for slashing of:
* BABE equivocations
* GRANDPA equivocations
* im-online offences https://github.com/paritytech/polkadot-sdk/blob/8b061a5c5d29a4ef8efa0f2919fdc5c3cfc36361/substrate/frame/im-online/src/lib.rs#L860
* BEEFY equivocations
* disputes

> Session? Do you mean era? Elections happen once per era AFAIK so that's 24h and NPoS elections are quite heavy to compute so they are computed some time in advance as well. If you are slashed at the end of an era I am genuinely not sure how it plays out with elections since it might invalidate some precomputed solutions. (Could that be an attack vector? By invalidating some solutions you could use your foreknowledge to make it so your solution wins the election... Need to investigate that more.)
> In general I was assuming a 24-48h window for getting organically kicked out after an election. So 1 era buffer (although that might be unrealistic). It is a defence in depth measure so having this time is better than having none (with instant direct disabling) and it only becomes relevant if there's a protocol mistake or nondeterminism we didn't anticipate.

Summoning @paritytech/staking-core to answer election questions (when exactly they happen and at what point slashing is/isn't accounted for).

-----------------------------------------

Some points from the call:
* we should probably consider validator disabled (e.g. in backing) if it is disabled in on of the active leafs
* "If limit reached simply no longer disable" probably works
* disable but not slash "against valid" voters
* disable and slash "for invalid" voters
* disabling should not affect consensus (e.g. disputes should conclude once confirmed)
* consider enabling block production for disabled as well

**Comment by burdges** [comment]
> * Backing is not allowed
> * Approval voting is allowed

These make perfect sense.  I'd add disabling does not touch grandpa either.

> * Dispute voting is allowed but limited (not escalated when coming from disabled nodes)

We're happy here overall, but we do technically alter the security analysis here.  We might identify & suggest other tweaks, like adjusting `needed_approvals` or tranche zero samples.

> Should block production be blocked for disabled validators?

No.  We've a spam dispute, but likely a some bug, not malicious.  We should address plausibly malicious block production activities elsewhere.

**Comment by eskimor** [comment]
More refinement as of today's call:

First of all @ordian would like to use the relay parent for determining the disabled state on the node side. The result would be that we use a different state on the node side as compared to the runtime. This should be "fine" though:

1. For disputes: There is no checking in the runtime anyway. All we do is refrain from participation.
2. For backing: We can be slightly out of sync, but there are not bad consequences:
First, the relay parent in backing can only be an ancestor of the current leaf. So we are strictly using an older (or identical) state than the runtime. This means for transitions enabled -> disabled, we might do redundant work for a few blocks in statement distribution. No harm done. For disabled -> enabled transition (very rare), a node would worst case effectively stay disabled a couple of more blocks -> also fine. Especially since this only happens in an absolute corner case, where we already are outside of byzantine assumptions. Enabling on era boundaries does not matter, as we ware clearing backed candidates on session boundaries anyway.

# State Pruning

State pruning should not be an issue for backing, because we only prune state on the canonical chain something like 250 blocks after finality. For abandoned forks this happens sooner, but we also don't care whether backing is successful or not on dead forks.

For disputes pruning is a problem, but the problem with era changes goes even deeper: Let's assume a validator is no longer in the active set after an era change. With the current system we now have absolutely no way of disabling such a validator (as the runtime no longer knows about it). Hence if it starts disputing only directly after the era change, it can cause a significant volume of spam: It can dispute all candidates on the unfinalized chain until the era change. If finality is not lagging, these might "only" be 100-200 disputes. If finality is lagging more, it could be thousands.

Using the relay parent here helps a bit, as then the least if the validator started disputing before the era change, we would preserve the disabled state. Still as described above (disputing only starts after era change), this does not fully alleviate the problem and further is brittle, as we might not be able to retrieve state for blocks of abandoned forks.

Given that disabling for disputes only has effect on the node side anyway (runtime is protected by importing only confirmed disputes), this can be mitigated by letting the dispute coordinator being able to disable nodes itself. It could for example keep disabled nodes of the previous session (as of the latest leaf it has seen of that session) until finality (including `DISPUTE_CANDIDATE_LIFETIME_AFTER_FINALIZATION`) has reached the current session.

For what state to use, it seems using the state of current leaves is more robust for disputes (+ persistence of previous session state until finality). For statement-distribution, either should be fine ... although using a different method only there would be odd.

@ordian @Overkillus @tdimitrov

**Comment by ordian** [comment]
If we agree to never re-enable a validator within a session, I'd propose we introduce a mapping of `disabled_validators: SessionIndex -> BTreeSet<ValidatorIndex>`, which is being updated on every active leaf by simply adding new disabled validators to the list. Then backing, statement-distribution and disputes use that API instead.

If that sounds reasonable, there are a few details to resolve:
* where to store this mapping? 
  * `RuntimeInfo` sounds like a good candidate - downside - it's not being used by either backing or statement-distribution (changing that sounds non-trivial). 
  * Another place could be runtime API cache, but then we would need to change the caching logic for it and ensure someone is calling the query for every active leaf to update it in time (note: need to avoid races) - downside - leaky abstraction - runtime API shouldn't know about this
  * each subsystem stores its own mapping - downside - duplication
* not persisting this mapping sounds the easiest, are we ok with that? we have the same assumption about pinning blocks - as long as there's one node that is online for dispute_period, we should be fine
* can we change this "never re-enable a validator within a session" assumption in the future?

**Comment by Overkillus** [comment]
> If we agree to never re-enable a validator within a session

Think we want to push this even further, I don't think we ever need to re-enable a validator within an era. Enabling them after a session will lead to them committing the offence again if they are buggy or malicious. The scope of disabling should be eras as the validator sets change in the scope of eras.

This might slightly alter the storage considerations. We can follow-up on the disputes call.

**Comment by eskimor** [comment]
> If we agree to never re-enable a validator within a session, I'd propose we introduce a mapping of disabled_validators: SessionIndex -> BTreeSet<ValidatorIndex>, which is being updated on every active leaf by simply adding new disabled validators to the list. Then backing, statement-distribution and disputes use that API instead.

I am not sure how this resolves the issue with era changes I described.

In particular I am not sure which problem you want to solve with this at all. :thinking:  .. Do you want to change the runtime API to only get us newly disabled nodes?

I might be missing something obvious ... it is quite late already. :sleepy:

**Comment by ordian** [comment]
> In particular I am not sure which problem you want to solve with this at all.

The implementation simplicity, ensuring we use only one strategy consistently across backing, statement-distribution and disputes on the node side. This API is meant to be stored on used on the node side only.

**Comment by Overkillus** [comment]
**Mini-guide for the current version of the disabling strategy:**
- If validator gets slashed (even 0%) we disable him in the runtime and on the node side.
- We only disable up to 1/3 of the validators.
- If there are more offenders than 1/3 of the set disable only the highest offenders. (Some will get re-enabled)
- Disablement lasts for 1 era.
- Disabled validators remain in the active validator set but have some limited permissions
- Disabled validators can no longer back candidates
- Disabled validators can participate in approval checking and their 'valid' votes behave normally. 'invalid' votes do not automatically escalate into disputes but they are logged and stored so they will be taken into account if a dispute arises from at least 1 honest non-disabled validator.
- Disabling does not affect GRANDPA at all
- Disabling does not block Block Authoring
- A Validator is considered disabled if he is disabled in at least one active child leaf of the chain that is in scope.

**Comment by Overkillus** [comment]
> First, imagine there's a way to disable honest validators without getting slashed (e.g. timed disputes). Then you vote invalid without getting disabled in the runtime. (re-enabling is only useful in this case if they back invalid candidates)

First of all attackers need to pull off a successful time dispute attack and get 1/3 of the network slashed (probably a minuscule amount if any at all based on if we have time disputes countermeasures). If they succeed they can:

> Then you vote `invalid` without getting disabled in the runtime.

I assume what you mean is they vote `invalid` on valid candidates AKA start spam disputes. Yes, in that case they would not get disabled. They could continue spamming the disputes effectively breaking sharding. The chain should still be secure although extremely slow. Biggest problem is the true perpetrator of the attack (the collator suggesting the carefully timed block) gets away scot free but this simply loops back into our time dispute countermeasures which might be needed to protect against it. If malicious guys would pay for this there is little gain except lowering our liveness temporarily. While lives is suffering we can investigate and check how exactly they managed to slash honest nodes and if we can protect against that specific flavour of nondeterminism in the future. Security wise we should be good.

> If disputed candidate is in the previous era, you can't even disable malicious validators (they might be not in the active set anymore).

Is this an issue tho? Disabling is there to reduce damage done in the current era so if they are already gone there's not much more damage they can cause. Generally the main bulk of the punishment comes from the slash which should still be applied even if they are no longer in the active validator set.

**Comment by eskimor** [comment]
> First, imagine there's a way to disable honest validators without getting slashed (e.g. timed disputes). 

I think we slash even in time disputes - or at least we can now. (Slashes are deferred, validators don't lose nominators, no chilling, ...)

> If disputed candidate is in the previous era, you can't even disable malicious validators (they might be not in the active set anymore).

Yep.


For the node side disabling data structures, I don't think the suggested one cuts it. I would propose the following (pseudo code):

```
lost_disputes: LruMap<SessionIndex, HashSet<ValidatorIndex>>
```
(lru size is session window)

We need this map for two reasons:

1. For handling offenses that happened in a past session. (Runtime can not disable validators which might no longer exist in the current session, yet they might still raise disputes for old session candidates.)
2. Using the relay parent is awesome because of determinism, _but_ with async backing and increasing the allowed depth of relay parents, we are getting slow in applying any disabling.

Now, on receiving a dispute message, what we would be doing is the following: 

1. We receive a dispute message for some session.
2. We lookup the disabled state based on the relay parent - if block does not exist, disabled state does not matter, because we would only participate if confirmed anyways. If it exists, we check how many validators are disabled.
3. If disabled as of (2) - don't participate, if not disabled based on (2) check count of validators disabled in (2). If below threshold, also check `lost_disputes` for the session of the disputed candidate - if found, don't participate. If (2) is already above threshold, then ignore `lost_disputes`. (We never want to risk consensus)

On concluding disputes, we add losing validators to `lost_disputes`.

With this strategy we are covering both (1) and (2), without risking any consensus issues. TL;DR: Only use the node side set, if disabled set in the runtime is not too large already.

**Comment by eskimor** [comment]
> Is this an issue tho?

Yes. There will always be at least 10 blocks (with forks and lacking finality maybe even significantly more) full with candidates that can be disputed of the previous session(s).  With 100 cores, we are talking about > 1000 candidates.

Now this validator can still dispute those candidates, even if no longer live in the current session. This can be quite a significant number of disputes and with our current 0% slash it would go completely unpunished:

1. The runtime can not disable that guy in the current session any more, because it is no longer active.
2. The validator would not lose out on any rewards at all, if he does it right at the end of the era - where it can no longer get disabled.

Now with the above algorithm, the guy would still go unpunished, but at least he the harm to the network would be minimized. This would actually be an argument for >0% slashes.

**Comment by Overkillus** [comment]
This is the most current design of the disabling strategy: https://github.com/paritytech/polkadot-sdk/pull/2955

Overall state done, only missing validator re-enabling. Can deploy with it missing but awaiting audit before deployment.
